<?php
/**
 * Slovník instalátoru: Slovenčina. Klíčem je český text z instalátoru (funkce t()), hodnotou překlad.
 * Patří sem i ukázkový obsah, který instalace zakládá (rubrika, uvítací článek, názvy bloků a šablon článku).
 */

return [
    'Instalace MiroCMS' => 'Inštalácia MiroCMS',
    'Instalace redakčního systému' => 'Inštalácia redakčného systému',
    'Čtyři krátké kroky a váš magazín běží. Vše lze později změnit v administraci.' => 'Štyri krátke kroky a váš magazín beží. Všetko možno neskôr zmeniť v administrácii.',
    'Kontrola serveru' => 'Kontrola servera',
    'Server nesplňuje požadavky. Opravte položky označené křížkem a obnovte stránku.' => 'Server nespĺňa požiadavky. Opravte položky označené krížikom a obnovte stránku.',
    'Instalaci se nepodařilo dokončit – zkontrolujte zvýrazněná pole.' => 'Inštaláciu sa nepodarilo dokončiť – skontrolujte zvýraznené polia.',
    'Databáze' => 'Databáza',
    'MySQL nebo MariaDB. Prázdnou databázi založte předem – na hostingu v jeho administraci.' => 'MySQL alebo MariaDB. Prázdnu databázu založte vopred – na hostingu v jeho administrácii.',
    'Název databáze' => 'Názov databázy',
    'Předpona tabulek' => 'Predpona tabuliek',
    'Uživatel' => 'Používateľ',
    'Účet, kterým se poprvé přihlásíte do administrace.' => 'Účet, ktorým sa prvýkrát prihlásite do administrácie.',
    'Název webu' => 'Názov webu',
    'Přihlašovací jméno' => 'Prihlasovacie meno',
    'Jméno a příjmení' => 'Meno a priezvisko',
    'Zobrazuje se u článků.' => 'Zobrazuje sa pri článkoch.',
    'Alespoň 10 znaků.' => 'Aspoň 10 znakov.',
    'Heslo znovu' => 'Heslo znova',
    'Podle něj se vydávají naplánované články a zobrazují data.' => 'Podľa neho sa vydávajú naplánované články a zobrazujú dátumy.',
    'Šablona webu' => 'Šablóna webu',
    'Jak uvidí magazín čtenáři.' => 'Ako uvidia magazín čitatelia.',
    'Nainstalovat MiroCMS' => 'Nainštalovať MiroCMS',
    'Vytvoří tabulky v databázi a soubor config.php.' => 'Vytvorí tabuľky v databáze a súbor config.php.',
    'MiroCMS je už nainstalován' => 'MiroCMS je už nainštalovaný',
    'Soubor config.php existuje, instalátor proto nic nemění.' => 'Súbor config.php existuje, inštalátor preto nič nemení.',
    'Hotovo, magazín běží' => 'Hotovo, magazín beží',
    'Databáze je připravena a konfigurace zapsána.' => 'Databáza je pripravená a konfigurácia zapísaná.',
    'Z bezpečnostních důvodů teď ze serveru smažte soubor' => 'Z bezpečnostných dôvodov teraz zo servera zmažte súbor',
    'Přejít do administrace' => 'Prejsť do administrácie',
    'Zobrazit web' => 'Zobraziť web',
    'Můj magazín' => 'Môj magazín',
    'běží' => 'beží',
    'připojení k databázi MySQL / MariaDB' => 'pripojenie k databáze MySQL / MariaDB',
    'práce s češtinou' => 'práca s diakritikou',
    'kvůli vytvoření config.php' => 'kvôli vytvoreniu config.php',
    'Předpona: malá písmena, číslice a podtržítko, nejvýše 16 znaků (např. mc_).' => 'Predpona: malé písmená, číslice a podčiarkovník, najviac 16 znakov (napr. mc_).',
    'Vyplňte název databáze a uživatele.' => 'Vyplňte názov databázy a používateľa.',
    'Přihlašovací jméno: 2-40 znaků, písmena bez diakritiky, číslice, tečka, pomlčka, podtržítko.' => 'Prihlasovacie meno: 2–40 znakov, písmená bez diakritiky, číslice, bodka, pomlčka, podčiarkovník.',
    'Heslo musí mít alespoň 10 znaků.' => 'Heslo musí mať aspoň 10 znakov.',
    'Hesla se neshodují.' => 'Heslá sa nezhodujú.',
    'K databázi se nepodařilo připojit:' => 'K databáze sa nepodarilo pripojiť:',
    'V databázi už tabulky s touto předponou existují. Zvolte jinou předponu, nebo je nejprve odstraňte.' => 'V databáze už tabuľky s touto predponou existujú. Zvoľte inú predponu, alebo ich najprv odstráňte.',
    'Vytvoření tabulek selhalo:' => 'Vytvorenie tabuliek zlyhalo:',
    'Tabulky jsou vytvořeny, ale nepodařilo se zapsat config.php. Zkontrolujte práva k zápisu.' => 'Tabuľky sú vytvorené, ale nepodarilo sa zapísať config.php. Skontrolujte práva na zápis.',
    'Základní' => 'Základný',
    'Standardní' => 'Štandardná',
    'Vítejte v MiroCMS' => 'Vitajte v MiroCMS',
    'Redakční systém je nainstalován a připraven. Tento článek můžete v administraci upravit nebo smazat.' => 'Redakčný systém je nainštalovaný a pripravený. Tento článok môžete v administrácii upraviť alebo zmazať.',
    'Do administrace se dostanete na adrese admin.php. Na přehledu vás provedou První kroky: dejte webu tvář, založte rubriky a napište první článek. Rozložení webu do sloupců a bloků upravíte přímo na stránce v sekci Bloky a rozvržení.' => 'Do administrácie sa dostanete na adrese admin.php. Na prehľade vás prevedú Prvé kroky: dajte webu tvár, založte rubriky a napíšte prvý článok. Rozloženie webu do stĺpcov a blokov upravíte priamo na stránke v sekcii Bloky a rozloženie.',
    'Dlouhé čtení' => 'Dlhé čítanie',
    'Vyhledávání' => 'Vyhľadávanie',
    'Nejčtenější články' => 'Najčítanejšie články',
    'Seriózní deník: patkové titulky, tenké linky, otvírák a sloupcová sazba ve stylu velkých světových novin.' => 'Seriózny denník: pätkové titulky, tenké linky, otvárák a stĺpcová sadzba v štýle veľkých svetových novín.',
    'Osobní magazín, blog nebo newsletterový web: jeden úzký sloupec, klidná typografie, seznam článků bez rušivých prvků.' => 'Osobný magazín, blog alebo newsletterový web: jeden úzky stĺpec, pokojná typografia, zoznam článkov bez rušivých prvkov.',
    'Výrazný online magazín: černá lišta, obří titulky, velké fotografie a mřížka karet.' => 'Výrazný online magazín: čierna lišta, obrie titulky, veľké fotografie a mriežka kariet.',
    'PHP 8.4 nebo novější' => 'PHP 8.4 alebo novšie',
    'Rozšíření pdo_mysql' => 'Rozšírenie pdo_mysql',
    'Rozšíření mbstring' => 'Rozšírenie mbstring',
    'Zápis do kořenové složky' => 'Zápis do koreňového priečinka',
    'Zápis do složky storage/' => 'Zápis do priečinka storage/',
    'Soubor install.php se z bezpečnostních důvodů smazal sám – nic dalšího dělat nemusíte.' => 'Súbor install.php sa z bezpečnostných dôvodov zmazal sám – nič ďalšie robiť nemusíte.',
    'Příručka: první kroky po instalaci' => 'Príručka: prvé kroky po inštalácii',
    'Nahrát ukázkový obsah' => 'Nahrať ukážkový obsah',
    'Rubriky, články a obrázky smyšleného magazínu, ať hned vidíte, jak web vypadá. Později ho jedním kliknutím smažete.' => 'Rubriky, články a obrázky vymysleného magazínu, aby ste hneď videli, ako web vyzerá. Neskôr ho jedným kliknutím zmažete.',
];
