<?php
/**
 * Slovník instalátoru: Deutsch. Klíčem je český text z instalátoru (funkce t()), hodnotou překlad.
 * Patří sem i ukázkový obsah, který instalace zakládá (rubrika, uvítací článek, názvy bloků a šablon článku).
 */

return [
    'Instalace MiroCMS' => 'MiroCMS-Installation',
    'Instalace redakčního systému' => 'Installation des Redaktionssystems',
    'Čtyři krátké kroky a váš magazín běží. Vše lze později změnit v administraci.' => 'Vier kurze Schritte und Ihr Magazin läuft. Alles lässt sich später in der Administration ändern.',
    'Kontrola serveru' => 'Serverprüfung',
    'Server nesplňuje požadavky. Opravte položky označené křížkem a obnovte stránku.' => 'Der Server erfüllt die Anforderungen nicht. Beheben Sie die mit einem Kreuz markierten Punkte und laden Sie die Seite neu.',
    'Instalaci se nepodařilo dokončit – zkontrolujte zvýrazněná pole.' => 'Die Installation konnte nicht abgeschlossen werden – prüfen Sie die markierten Felder.',
    'Databáze' => 'Datenbank',
    'MySQL nebo MariaDB. Prázdnou databázi založte předem – na hostingu v jeho administraci.' => 'MySQL oder MariaDB. Legen Sie vorher eine leere Datenbank an – in der Verwaltung Ihres Hostings.',
    'Název databáze' => 'Datenbankname',
    'Předpona tabulek' => 'Tabellenpräfix',
    'Uživatel' => 'Benutzer',
    'Heslo' => 'Passwort',
    'Web a administrátor' => 'Website und Administrator',
    'Účet, kterým se poprvé přihlásíte do administrace.' => 'Das Konto, mit dem Sie sich zum ersten Mal in der Administration anmelden.',
    'Název webu' => 'Name der Website',
    'Přihlašovací jméno' => 'Benutzername',
    'Jméno a příjmení' => 'Vor- und Nachname',
    'Zobrazuje se u článků.' => 'Wird bei Artikeln angezeigt.',
    'E-mail' => 'E-Mail',
    'Alespoň 10 znaků.' => 'Mindestens 10 Zeichen.',
    'Heslo znovu' => 'Passwort wiederholen',
    'Časové pásmo' => 'Zeitzone',
    'Podle něj se vydávají naplánované články a zobrazují data.' => 'Danach werden geplante Artikel veröffentlicht und Datumsangaben angezeigt.',
    'Šablona webu' => 'Vorlage der Website',
    'Jak uvidí magazín čtenáři.' => 'So sehen die Leser das Magazin.',
    'Nainstalovat MiroCMS' => 'MiroCMS installieren',
    'Vytvoří tabulky v databázi a soubor config.php.' => 'Erstellt die Tabellen in der Datenbank und die Datei config.php.',
    'MiroCMS je už nainstalován' => 'MiroCMS ist bereits installiert',
    'Soubor config.php existuje, instalátor proto nic nemění.' => 'Die Datei config.php existiert, das Installationsprogramm ändert daher nichts.',
    'Hotovo, magazín běží' => 'Fertig, Ihr Magazin läuft',
    'Databáze je připravena a konfigurace zapsána.' => 'Die Datenbank ist bereit und die Konfiguration wurde geschrieben.',
    'Z bezpečnostních důvodů teď ze serveru smažte soubor' => 'Löschen Sie aus Sicherheitsgründen jetzt diese Datei vom Server:',
    'Přejít do administrace' => 'Zur Administration',
    'Zobrazit web' => 'Website ansehen',
    'Můj magazín' => 'Mein Magazin',
    'běží' => 'läuft',
    'připojení k databázi MySQL / MariaDB' => 'Verbindung zur MySQL-/MariaDB-Datenbank',
    'práce s češtinou' => 'Arbeit mit Umlauten und Sonderzeichen (UTF-8)',
    'kvůli vytvoření config.php' => 'zum Anlegen der config.php',
    'logy a cache' => 'Protokolle und Cache',
    'Předpona: malá písmena, číslice a podtržítko, nejvýše 16 znaků (např. mc_).' => 'Präfix: Kleinbuchstaben, Ziffern und Unterstrich, höchstens 16 Zeichen (z. B. mc_).',
    'Vyplňte název databáze a uživatele.' => 'Geben Sie Datenbankname und Benutzer an.',
    'Přihlašovací jméno: 2-40 znaků, písmena bez diakritiky, číslice, tečka, pomlčka, podtržítko.' => 'Benutzername: 2–40 Zeichen, Buchstaben ohne Sonderzeichen, Ziffern, Punkt, Bindestrich, Unterstrich.',
    'Heslo musí mít alespoň 10 znaků.' => 'Das Passwort muss mindestens 10 Zeichen lang sein.',
    'Hesla se neshodují.' => 'Die Passwörter stimmen nicht überein.',
    'E-mail nemá platný tvar.' => 'Die E-Mail-Adresse ist ungültig.',
    'K databázi se nepodařilo připojit:' => 'Verbindung zur Datenbank fehlgeschlagen:',
    'V databázi už tabulky s touto předponou existují. Zvolte jinou předponu, nebo je nejprve odstraňte.' => 'In der Datenbank existieren bereits Tabellen mit diesem Präfix. Wählen Sie ein anderes Präfix oder entfernen Sie sie zuerst.',
    'Vytvoření tabulek selhalo:' => 'Das Anlegen der Tabellen ist fehlgeschlagen:',
    'Tabulky jsou vytvořeny, ale nepodařilo se zapsat config.php. Zkontrolujte práva k zápisu.' => 'Die Tabellen wurden angelegt, aber config.php konnte nicht geschrieben werden. Prüfen Sie die Schreibrechte.',
    'Základní' => 'Basis',
    'Standardní' => 'Standard',
    'Aktuality' => 'Aktuelles',
    'Vítejte v MiroCMS' => 'Willkommen bei MiroCMS',
    'Redakční systém je nainstalován a připraven. Tento článek můžete v administraci upravit nebo smazat.' => 'Das Redaktionssystem ist installiert und bereit. Diesen Artikel können Sie in der Administration bearbeiten oder löschen.',
    'Do administrace se dostanete na adrese admin.php. Na přehledu vás provedou První kroky: dejte webu tvář, založte rubriky a napište první článek. Rozložení webu do sloupců a bloků upravíte přímo na stránce v sekci Bloky a rozvržení.' => 'Die Administration erreichen Sie unter admin.php. Auf der Übersicht führen Sie die Ersten Schritte: Geben Sie der Website ein Gesicht, legen Sie Ressorts an und schreiben Sie den ersten Artikel. Die Aufteilung der Website in Spalten und Blöcke bearbeiten Sie direkt auf der Seite im Bereich Blöcke und Layout.',
    'Dlouhé čtení' => 'Longread',
    'Fotoreportáž' => 'Fotoreportage',
    'Rozhovor' => 'Interview',
    'Rubriky' => 'Ressorts',
    'Vyhledávání' => 'Suche',
    'Nejčtenější články' => 'Meistgelesen',
    'Seriózní deník: patkové titulky, tenké linky, otvírák a sloupcová sazba ve stylu velkých světových novin.' => 'Seriöse Tageszeitung: Serifen-Überschriften, feine Linien, Aufmacher und Spaltensatz im Stil der großen Zeitungen der Welt.',
    'Osobní magazín, blog nebo newsletterový web: jeden úzký sloupec, klidná typografie, seznam článků bez rušivých prvků.' => 'Persönliches Magazin, Blog oder Newsletter-Website: eine schmale Spalte, ruhige Typografie, Artikelliste ohne Ablenkung.',
    'Výrazný online magazín: černá lišta, obří titulky, velké fotografie a mřížka karet.' => 'Markantes Online-Magazin: schwarze Leiste, riesige Überschriften, große Fotos und ein Kartenraster.',
    'PHP 8.4 nebo novější' => 'PHP 8.4 oder neuer',
    'Rozšíření pdo_mysql' => 'Erweiterung pdo_mysql',
    'Rozšíření mbstring' => 'Erweiterung mbstring',
    'Zápis do kořenové složky' => 'Schreibzugriff auf das Stammverzeichnis',
    'Zápis do složky storage/' => 'Schreibzugriff auf den Ordner storage/',
    'Soubor install.php se z bezpečnostních důvodů smazal sám – nic dalšího dělat nemusíte.' => 'Die Datei install.php hat sich aus Sicherheitsgründen selbst gelöscht – Sie müssen nichts weiter tun.',
    'Příručka: první kroky po instalaci' => 'Handbuch: die ersten Schritte nach der Installation',
    'Podrobný návod' => 'Ausführliche Anleitung',
    'Nahrát ukázkový obsah' => 'Beispielinhalte laden',
    'Rubriky, články a obrázky smyšleného magazínu, ať hned vidíte, jak web vypadá. Později ho jedním kliknutím smažete.' => 'Ressorts, Artikel und Bilder eines erfundenen Magazins, damit Sie sofort sehen, wie die Website aussieht. Später löschen Sie sie mit einem Klick.',
];
