<?php

// Instalátor anglicky. Klíčem je český text z views/install a Install\Installer.

return [
    'Instalace MiroCMS' => 'MiroCMS installation',
    'Tři krátké kroky a váš web běží. Vše lze později změnit v administraci.' => 'Three short steps and your website is running. Everything can be changed later in the administration.',
    'Kontrola serveru' => 'Server check',
    'Server nesplňuje požadavky. Opravte položky označené křížkem a obnovte stránku.' => 'The server does not meet the requirements. Fix the items marked with a cross and reload the page.',
    'Instalaci se nepodařilo dokončit – zkontrolujte zvýrazněná pole.' => 'The installation could not be completed – check the highlighted fields.',
    'Databáze' => 'Database',
    'MySQL nebo MariaDB. Prázdnou databázi založte předem – na hostingu v jeho administraci.' => 'MySQL or MariaDB. Create an empty database beforehand – in your hosting control panel.',
    'Název databáze' => 'Database name',
    'Předpona tabulek' => 'Table prefix',
    'Uživatel' => 'User',
    'Heslo' => 'Password',
    'Web a administrátor' => 'Site and administrator',
    'Účet, kterým se poprvé přihlásíte do administrace.' => 'The account you will first sign in to the administration with.',
    'Název webu' => 'Site name',
    'Přihlašovací jméno' => 'Username',
    'Jméno a příjmení' => 'Full name',
    'Zobrazuje se u novinek.' => 'Shown with news posts.',
    'Alespoň 10 znaků.' => 'At least 10 characters.',
    'Heslo znovu' => 'Password again',
    'Časové pásmo' => 'Time zone',
    'Podle něj se vydávají naplánované novinky a zobrazují data.' => 'Scheduled news posts are published and dates are shown according to it.',
    'Nainstalovat MiroCMS' => 'Install MiroCMS',
    'Vytvoří tabulky v databázi a soubor config.php.' => 'Creates the database tables and the config.php file.',
    'MiroCMS je už nainstalován' => 'MiroCMS is already installed',
    'Soubor config.php existuje, instalátor proto nic nemění.' => 'The config.php file exists, so the installer changes nothing.',
    'Hotovo, web běží' => 'Done, your website is running',
    'Databáze je připravena a konfigurace zapsána.' => 'The database is ready and the configuration has been written.',
    'Soubor install.php se z bezpečnostních důvodů smazal sám – nic dalšího dělat nemusíte.' => 'For security reasons install.php has deleted itself – there is nothing else you need to do.',
    'Z bezpečnostních důvodů teď ze serveru smažte soubor' => 'For security reasons, now delete this file from the server:',
    'Přejít do administrace' => 'Go to the administration',
    'Zobrazit web' => 'View the site',
    'Můj web' => 'My website',
    'běží' => 'running',
    'připojení k databázi MySQL / MariaDB' => 'connection to a MySQL / MariaDB database',
    'práce s češtinou' => 'working with accented text (UTF-8)',
    'kvůli vytvoření config.php' => 'needed to create config.php',
    'logy a cache' => 'logs and cache',
    'Předpona: malá písmena, číslice a podtržítko, nejvýše 16 znaků (např. mc_).' => 'Prefix: lowercase letters, digits and underscore, at most 16 characters (e.g. mc_).',
    'Vyplňte název databáze a uživatele.' => 'Fill in the database name and user.',
    'Přihlašovací jméno: 2-40 znaků, písmena bez diakritiky, číslice, tečka, pomlčka, podtržítko.' => 'Username: 2–40 characters, letters without accents, digits, dot, hyphen, underscore.',
    'Heslo musí mít alespoň 10 znaků.' => 'The password must be at least 10 characters long.',
    'Hesla se neshodují.' => 'The passwords do not match.',
    'E-mail nemá platný tvar.' => 'The e-mail address is not valid.',
    'K databázi se nepodařilo připojit:' => 'Could not connect to the database:',
    'V databázi už tabulky s touto předponou existují. Zvolte jinou předponu, nebo je nejprve odstraňte.' => 'Tables with this prefix already exist in the database. Choose another prefix or remove them first.',
    'Vytvoření tabulek selhalo:' => 'Creating the tables failed:',
    'Tabulky jsou vytvořeny, ale nepodařilo se zapsat config.php. Zkontrolujte práva k zápisu.' => 'The tables were created, but config.php could not be written. Check the write permissions.',
    'Úvod' => 'Home',
    'Jednou větou: co děláte a pro koho. Tuto stránku upravíte v administraci v sekci Stránky.' => 'In one sentence: what you do and for whom. Edit this page in the administration under Pages.',
    'O nás' => 'About us',
    'Kdo jste, jak dlouho to děláte a proč vám zákazníci věří.' => 'Who you are, how long you have been doing it and why customers trust you.',
    'Služby' => 'Services',
    'Co nabízíte – každou službu krátce a srozumitelně.' => 'What you offer – each service briefly and clearly.',
    'Kontakt' => 'Contact',
    'Adresa, telefon, e-mail a otevírací doba.' => 'Address, phone, e-mail and opening hours.',
    'Aktuality' => 'News',
    'Vítejte v MiroCMS' => 'Welcome to MiroCMS',
    'Web je nainstalovaný a připravený. Tuto novinku můžete v administraci upravit nebo smazat.' => 'The website is installed and ready. You can edit or delete this news post in the administration.',
    'Do administrace se dostanete na adrese admin.php. Na přehledu vás provedou První kroky: dejte webu tvář, vyplňte údaje o firmě a připravte stránky.' => 'The administration is at admin.php. On the dashboard, First steps will guide you: give the website its look, fill in your company details and prepare the pages.',
];
