<?php
/**
 * Slovník instalátoru: English. Klíčem je český text z instalátoru (funkce t()), hodnotou překlad.
 * Patří sem i ukázkový obsah, který instalace zakládá (rubrika, uvítací článek, názvy bloků a šablon článku).
 */

return [
    'Instalace MiroCMS' => 'MiroCMS installation',
    'Instalace redakčního systému' => 'Install the publishing system',
    'Čtyři krátké kroky a váš magazín běží. Vše lze později změnit v administraci.' => 'Four short steps and your magazine is running. Everything can be changed later in the administration.',
    'Kontrola serveru' => 'Server check',
    'Server nesplňuje požadavky. Opravte položky označené křížkem a obnovte stránku.' => 'The server does not meet the requirements. Fix the items marked with a cross and reload the page.',
    'Instalaci se nepodařilo dokončit – zkontrolujte zvýrazněná pole.' => 'The installation could not be completed – check the highlighted fields.',
    'Databáze' => 'Database',
    'MySQL nebo MariaDB. Prázdnou databázi založte předem – na hostingu v jeho administraci.' => 'MySQL or MariaDB. Create an empty database beforehand – in your hosting control panel.',
    'Název databáze' => 'Database name',
    'Předpona tabulek' => 'Table prefix',
    'Uživatel' => 'User',
    'Heslo' => 'Password',
    'Web a administrátor' => 'Site and administrator',
    'Účet, kterým se poprvé přihlásíte do administrace.' => 'The account you will first sign in to the administration with.',
    'Název webu' => 'Site name',
    'Přihlašovací jméno' => 'Username',
    'Jméno a příjmení' => 'Full name',
    'Zobrazuje se u článků.' => 'Shown with articles.',
    'Alespoň 10 znaků.' => 'At least 10 characters.',
    'Heslo znovu' => 'Password again',
    'Časové pásmo' => 'Time zone',
    'Podle něj se vydávají naplánované články a zobrazují data.' => 'Scheduled articles are published and dates are shown according to it.',
    'Šablona webu' => 'Site template',
    'Jak uvidí magazín čtenáři.' => 'How readers will see the magazine.',
    'Nainstalovat MiroCMS' => 'Install MiroCMS',
    'Vytvoří tabulky v databázi a soubor config.php.' => 'Creates the database tables and the config.php file.',
    'MiroCMS je už nainstalován' => 'MiroCMS is already installed',
    'Soubor config.php existuje, instalátor proto nic nemění.' => 'The config.php file exists, so the installer changes nothing.',
    'Hotovo, magazín běží' => 'Done, your magazine is running',
    'Databáze je připravena a konfigurace zapsána.' => 'The database is ready and the configuration has been written.',
    'Z bezpečnostních důvodů teď ze serveru smažte soubor' => 'For security reasons, now delete this file from the server:',
    'Přejít do administrace' => 'Go to the administration',
    'Zobrazit web' => 'View the site',
    'Můj magazín' => 'My magazine',
    'běží' => 'running',
    'připojení k databázi MySQL / MariaDB' => 'connection to a MySQL / MariaDB database',
    'práce s češtinou' => 'working with accented text (UTF-8)',
    'kvůli vytvoření config.php' => 'needed to create config.php',
    'logy a cache' => 'logs and cache',
    'Předpona: malá písmena, číslice a podtržítko, nejvýše 16 znaků (např. mc_).' => 'Prefix: lowercase letters, digits and underscore, at most 16 characters (e.g. mc_).',
    'Vyplňte název databáze a uživatele.' => 'Fill in the database name and user.',
    'Přihlašovací jméno: 2-40 znaků, písmena bez diakritiky, číslice, tečka, pomlčka, podtržítko.' => 'Username: 2–40 characters, letters without accents, digits, dot, hyphen, underscore.',
    'Heslo musí mít alespoň 10 znaků.' => 'The password must be at least 10 characters long.',
    'Hesla se neshodují.' => 'The passwords do not match.',
    'E-mail nemá platný tvar.' => 'The e-mail address is not valid.',
    'K databázi se nepodařilo připojit:' => 'Could not connect to the database:',
    'V databázi už tabulky s touto předponou existují. Zvolte jinou předponu, nebo je nejprve odstraňte.' => 'Tables with this prefix already exist in the database. Choose another prefix or remove them first.',
    'Vytvoření tabulek selhalo:' => 'Creating the tables failed:',
    'Tabulky jsou vytvořeny, ale nepodařilo se zapsat config.php. Zkontrolujte práva k zápisu.' => 'The tables were created, but config.php could not be written. Check the write permissions.',
    'Základní' => 'Basic',
    'Standardní' => 'Standard',
    'Aktuality' => 'News',
    'Vítejte v MiroCMS' => 'Welcome to MiroCMS',
    'Redakční systém je nainstalován a připraven. Tento článek můžete v administraci upravit nebo smazat.' => 'The publishing system is installed and ready. You can edit or delete this article in the administration.',
    'Do administrace se dostanete na adrese admin.php. Na přehledu vás provedou První kroky: dejte webu tvář, založte rubriky a napište první článek. Rozložení webu do sloupců a bloků upravíte přímo na stránce v sekci Bloky a rozvržení.' => 'You reach the administration at admin.php. The First steps on the overview will guide you: give the site a face, create sections and write your first article. You arrange the site into columns and blocks right on the page, under Blocks and layout.',
    'Dlouhé čtení' => 'Long read',
    'Fotoreportáž' => 'Photo story',
    'Rozhovor' => 'Interview',
    'Rubriky' => 'Sections',
    'Vyhledávání' => 'Search',
    'Nejčtenější články' => 'Most read',
    'Seriózní deník: patkové titulky, tenké linky, otvírák a sloupcová sazba ve stylu velkých světových novin.' => 'A serious daily: serif headlines, thin rules, a lead story and column setting in the style of the great newspapers.',
    'Osobní magazín, blog nebo newsletterový web: jeden úzký sloupec, klidná typografie, seznam článků bez rušivých prvků.' => 'A personal magazine, blog or newsletter site: one narrow column, calm typography, a list of articles without distractions.',
    'Výrazný online magazín: černá lišta, obří titulky, velké fotografie a mřížka karet.' => 'A bold online magazine: black bar, huge headlines, large photographs and a grid of cards.',
    'PHP 8.4 nebo novější' => 'PHP 8.4 or newer',
    'Rozšíření pdo_mysql' => 'pdo_mysql extension',
    'Rozšíření mbstring' => 'mbstring extension',
    'Zápis do kořenové složky' => 'Write access to the root folder',
    'Zápis do složky storage/' => 'Write access to the storage/ folder',
    'Soubor install.php se z bezpečnostních důvodů smazal sám – nic dalšího dělat nemusíte.' => 'For security reasons install.php has deleted itself – there is nothing else you need to do.',
    'Příručka: první kroky po instalaci' => 'Manual: first steps after installation',
    'Podrobný návod' => 'Detailed guide',
    'Nahrát ukázkový obsah' => 'Load sample content',
    'Rubriky, články a obrázky smyšleného magazínu, ať hned vidíte, jak web vypadá. Později ho jedním kliknutím smažete.' => 'Sections, articles and images of a fictional magazine, so you can see right away what the site looks like. You can delete it later with one click.',
];
