/* MiroCMS - překlad textů skriptů administrace (sk). Klíčem je český text ze skriptů (funkce T()). */
window.MIROCMS_PREKLAD = {
	"rozepsaný text uložen i na serveru ": "rozpísaný text uložený aj na serveri ",
	"Na serveru je neuložená rozepsaná verze z ": "Na serveri je neuložená rozpísaná verzia z ",

	"nebo": "alebo",
	"…nebo najděte vlastní článek": "…alebo nájdite vlastný článok",
	"část titulku": "časť titulku",
	"otevřít v novém okně": "otvoriť v novom okne",
	"Vložit odkaz": "Vložiť odkaz",
	"Zrušit odkaz": "Zrušiť odkaz",
	"Nic nenalezeno.": "Nič sa nenašlo.",
	"nevydaný": "nevydaný",

	"tabulka": "tabuľka",
	"Vložit tabulku 3 × 3 se záhlavím; řádky a sloupce pak přidáte tlačítky nad tabulkou": "Vložiť tabuľku 3 × 3 s hlavičkou; riadky a stĺpce potom pridáte tlačidlami nad tabuľkou",
	"+ řádek": "+ riadok",
	"+ sloupec": "+ stĺpec",
	"− řádek": "− riadok",
	"− sloupec": "− stĺpec",
	"smazat tabulku": "zmazať tabuľku",

	"Nahrání se nezdařilo. Zkontrolujte připojení a zkuste to znovu.": "Nahranie zlyhalo. Skontrolujte pripojenie a skúste to znova.",
	"Odstavec": "Odsek",
	"Mezititulek": "Medzititulok",
	"Menší mezititulek": "Menší medzititulok",
	"Tučně (Ctrl+B)": "Tučné (Ctrl+B)",
	"Vložit odkaz (Ctrl+K)": "Vložiť odkaz (Ctrl+K)",
	"• seznam": "• zoznam",
	"1. seznam": "1. zoznam",
	"Odrážkový seznam": "Odrážkový zoznam",
	"Číslovaný seznam": "Číslovaný zoznam",
	"„citace“": "„citát“",
	"Citace": "Citát",
	"obrázek": "obrázok",
	"galerie": "galéria",
	"Vložit obrázek z médií": "Vložiť obrázok z médií",
	"Fotogalerie": "Fotogaléria",
	"Vložit fotogalerii - čtenář si fotky prolistuje přes celou obrazovku": "Vložiť fotogalériu – čitateľ si fotky prelistuje na celej obrazovke",
	"Oddělovací čára": "Oddeľovacia čiara",
	"Odstranit formátování": "Odstrániť formátovanie",
	"Adresa odkazu (prázdné = odkaz zrušit):": "Adresa odkazu (prázdne = odkaz zrušiť):",
	" · čtení asi ": " · čítanie asi ",
	"Přepnout na zdrojový kód": "Prepnúť na zdrojový kód",
	"rozepsaný text uložen v prohlížeči ": "rozpísaný text uložený v prehliadači ",
	"V prohlížeči je neuložená rozepsaná verze z ": "V prehliadači je neuložená rozpísaná verzia z ",
	"Vybrat z médií": "Vybrať z médií",
	"Vložit galerii (": "Vložiť galériu (",
	"Klepnutím označte fotky v pořadí, v jakém mají jít za sebou. Soubory sem můžete i přetáhnout.": "Kliknutím označte fotky v poradí, v akom majú ísť za sebou. Súbory sem môžete aj pretiahnuť.",
	"Klepnutím obrázek vložíte. Soubory sem můžete i přetáhnout - nahrají se do zvolené složky.": "Kliknutím obrázok vložíte. Súbory sem môžete aj pretiahnuť – nahrajú sa do zvoleného priečinka.",
	"Načítám…": "Načítavam…",
	"Všechna média": "Všetky médiá",
	"Nezařazené": "Nezaradené",
	"Složka: ": "Priečinok: ",
	"Tady zatím žádné obrázky nejsou.": "Zatiaľ tu nie sú žiadne obrázky.",
	"co je na obrázku vidět": "čo je na obrázku vidieť",
	"Popis obrázku pro nevidomé čtenáře": "Popis obrázka pre nevidiacich čitateľov",
	"Obrázek bez popisu – nevidomý čtenář ani vyhledávač neví, co na něm je. Popis doplňte a potvrďte Enterem:": "Obrázok bez popisu – nevidiaci čitateľ ani vyhľadávač nevie, čo na ňom je. Popis doplňte a potvrďte Enterom:",
	"Navrhnout popis asistentem": "Navrhnúť popis asistentom",
	"Asistent nic nenavrhl.": "Asistent nič nenavrhol.",
	"Mezititulek „": "Medzititulok „",
	"“ přeskakuje úroveň (H": " “ preskakuje úroveň (H",
	" nad sebou). Čtečky podle úrovní skládají osnovu článku.": " nad sebou). Čítačky podľa úrovní skladajú osnovu článku.",
	"Prázdný mezititulek – smažte ho.": "Prázdny medzititulok – zmažte ho.",
	"“ neříká, kam vede. Odkazujte slovy, která dávají smysl i sama o sobě.": "“ nehovorí, kam vedie. Odkazujte slovami, ktoré dávajú zmysel aj samy osebe.",
	"Tabulka nemá záhlaví (buňky TH) – čtečka neumí říct, co který sloupec znamená.": "Tabuľka nemá hlavičku (bunky TH) – čítačka nevie povedať, čo ktorý stĺpec znamená.",
	"Vložené video nebo rámec nemá název (atribut title).": "Vložené video alebo rám nemá názov (atribút title).",
	"Titulek má přes 110 znaků – ve výsledcích hledání i na sítích se ořízne.": "Titulok má vyše 110 znakov – vo výsledkoch hľadania aj na sieťach sa oreže.",
	"Titulek psaný VERZÁLKAMI se špatně čte a čtečky ho mohou hláskovat.": "Titulok písaný VERZÁLKAMI sa zle číta a čítačky ho môžu hláskovať.",
	"Chybí perex – výpisy článků a sdílení na sítích ho potřebují.": "Chýba perex – výpisy článkov a zdieľanie na sieťach ho potrebujú.",
	"Kontrola přístupnosti": "Kontrola prístupnosti",
	"✓ Obrázky mají popisy, nadpisy i odkazy jsou v pořádku.": "✓ Obrázky majú popisy, nadpisy aj odkazy sú v poriadku.",
	"Spojení s asistentem selhalo. Zkuste to znovu.": "Spojenie s asistentom zlyhalo. Skúste to znova.",
	"Navrhnout": "Navrhnúť",
	"Korektura": "Korektúra",
	"Shrnutí „Ve zkratce“": "Zhrnutie „V skratke“",
	"Popis pro vyhledávače": "Popis pre vyhľadávače",
	"Návrh štítků": "Návrh štítkov",
	"Použít": "Použiť",
	"Asistent nic nenavrhl. Zkuste to znovu.": "Asistent nič nenavrhol. Skúste to znova.",
	"Návrh se jen vloží do pole – můžete ho dál upravit. Nic se neuloží, dokud článek neuložíte.": "Návrh sa len vloží do poľa – môžete ho ďalej upraviť. Nič sa neuloží, kým článok neuložíte.",
	"✓ Asistent nenašel nic k opravě.": "✓ Asistent nenašiel nič na opravu.",
	" – úsek prochází formátováním, opravte ho prosím ručně": " – úsek prechádza formátovaním, opravte ho prosím ručne",
	"Opravit označené": "Opraviť označené",
	"Asistent zkontroluje pravopis, překlepy a typografii": "Asistent skontroluje pravopis, preklepy a typografiu",
	"Asistent navrhne znění podle textu článku": "Asistent navrhne znenie podľa textu článku",
	"✦ přemýšlím…": "✦ premýšľam…",
	"Ukládám…": "Ukladám…",
	"Pořadí uloženo.": "Poradie uložené.",
	"Pořadí se nepodařilo uložit.": "Poradie sa nepodarilo uložiť.",
	"Média": "Médiá",
	"Nahrát nový": "Nahrať nový",
	"Vložit galerii": "Vložiť galériu",
	"Zavřít": "Zavrieť",
	"Ano, provést": "Áno, vykonať",
	"Zrušit": "Zrušiť",
	"Obnovit ji": "Obnoviť ju",
	"Zahodit": "Zahodiť",
	"Nic takového tu není.": "Nič také tu nie je.",
	"článek": "článok",
	"článek – nevydaný": "článok – nevydaný",
	"Vyfotit": "Odfotiť",
	" Blok dočasně skrýt": " Blok dočasne skryť",
	" Zobrazit nadpis na webu": " Zobraziť nadpis na webe",
	"+ další odkaz": "+ ďalší odkaz",
	"/o-nas nebo https://…": "/o-nas alebo https://…",
	"Adresa": "Adresa",
	"Bannery se spravují v sekci Reklama.": "Bannery sa spravujú v sekcii Reklama.",
	"Blok se přidá do zóny „": "Blok sa pridá do zóny „",
	"Blok smazán": "Blok zmazaný",
	"Bloky přetahujte myší. Najetím na blok se ukáže jeho ovládání.": "Bloky presúvajte myšou. Po prejdení na blok sa ukáže jeho ovládanie.",
	"Běžný": "Bežný",
	"Co chcete přidat?": "Čo chcete pridať?",
	"Hotovo": "Hotovo",
	"Jazyková verze": "Jazyková verzia",
	"Jedna až dvě věty. Prázdné = výchozí text.": "Jedna až dve vety. Prázdne = predvolený text.",
	"Jen v rubrice": "Len v rubrike",
	"Kam tlačítko vede": "Kam tlačidlo vedie",
	"Kdy a kde blok zobrazit": "Kedy a kde blok zobraziť",
	"Kolik položek": "Koľko položiek",
	"Nadpis": "Nadpis",
	"Nastavit": "Nastaviť",
	"Nejnovější ze všech rubrik": "Najnovšie zo všetkých rubrík",
	"Obsah": "Obsah",
	"Odebrat odkaz": "Odobrať odkaz",
	"Odkazy": "Odkazy",
	"Platební odkaz (Stripe, Donio, Darujme, Ko-fi…) nebo vlastní stránka s číslem účtu a QR kódem.": "Platobný odkaz (Stripe, Donio, Darujme, Ko-fi…) alebo vlastná stránka s číslom účtu a QR kódom.",
	"Podbarvený": "Podfarbený",
	"Podpořit redakci": "Podporiť redakciu",
	"Posunout níž": "Posunúť nižšie",
	"Posunout výš": "Posunúť vyššie",
	"Pořadí se nepodařilo uložit": "Poradie sa nepodarilo uložiť",
	"Pořadí uloženo": "Poradie uložené",
	"Reklamní pozice": "Reklamná pozícia",
	"Rozvržení:": "Rozloženie:",
	"Rubrika": "Rubrika",
	"Smazat blok": "Zmazať blok",
	"Smazat blok „": "Zmazať blok „",
	"Stránky": "Stránky",
	"Text": "Text",
	"Text odkazu": "Text odkazu",
	"Text tlačítka": "Text tlačidla",
	"Text, obrázek z médií nebo vložený kód (přepněte na HTML).": "Text, obrázok z médií alebo vložený kód (prepnite na HTML).",
	"Uložení se nezdařilo": "Uloženie sa nepodarilo",
	"Uložit": "Uložiť",
	"V rámečku": "V rámčeku",
	"Vzhled": "Vzhľad",
	"Výzva": "Výzva",
	"Zařízení": "Zariadenie",
	"Zvýrazněný nadpis": "Zvýraznený nadpis",
	"ve všech": "vo všetkých",
	"Úprava bloků": "Úprava blokov",
	"“. Nastavení můžete kdykoli změnit.": "“. Nastavenie môžete kedykoľvek zmeniť.",
	"Hlavička": "Hlavička",
	"Levý sloupec": "Ľavý stĺpec",
	"Nad obsahem": "Nad obsahom",
	"Pod obsahem": "Pod obsahom",
	"Pravý sloupec": "Pravý stĺpec",
	"Patička": "Pätička",
	"+ Přidat blok": "+ Pridať blok",
	"Složka": "Priečinok",
	"Načíst další": "Načítať ďalšie",
	"Hledat v médiích…": "Hľadať v médiách…",
	"Hledat v médiích": "Hľadať v médiách",
	"Hledanému textu nic neodpovídá.": "Hľadanému textu nič nezodpovedá.",
	"Období": "Obdobie",
	"Počítá se z vlastní statistiky návštěv; bez ní podle celkového počtu přečtení.": "Počíta sa z vlastnej štatistiky návštev; bez nej podľa celkového počtu prečítaní."
};
