/* Kaleta - překlad textů skriptů administrace (en). Klíčem je český text ze skriptů (funkce T()). */
window.KALETA_PREKLAD = {
	"rozepsaný text uložen i na serveru ": "draft also saved on the server at ",
	"Na serveru je neuložená rozepsaná verze z ": "The server holds an unsaved draft from ",

	"Odkaz": "Link",
	"Adresa": "Address",
	"nebo": "or",
	"část titulku": "part of the headline",
	"otevřít v novém okně": "open in a new window",
	"Vložit odkaz": "Insert link",
	"Zrušit odkaz": "Remove link",
	"Nic nenalezeno.": "Nothing found.",
	"nevydaný": "unpublished",

	"tabulka": "table",
	"Vložit tabulku 3 × 3 se záhlavím; řádky a sloupce pak přidáte tlačítky nad tabulkou": "Insert a 3 × 3 table with a header; add rows and columns with the buttons above the table",
	"+ řádek": "+ row",
	"+ sloupec": "+ column",
	"− řádek": "− row",
	"− sloupec": "− column",
	"smazat tabulku": "delete table",

	" slov": " words",
	"Nahrání se nezdařilo. Zkontrolujte připojení a zkuste to znovu.": "Upload failed. Check your connection and try again.",
	"Odstavec": "Paragraph",
	"Mezititulek": "Subheading",
	"Menší mezititulek": "Smaller subheading",
	"Tučně (Ctrl+B)": "Bold (Ctrl+B)",
	"Kurzíva (Ctrl+I)": "Italic (Ctrl+I)",
	"odkaz": "link",
	"Vložit odkaz (Ctrl+K)": "Insert link (Ctrl+K)",
	"• seznam": "• list",
	"1. seznam": "1. list",
	"Odrážkový seznam": "Bulleted list",
	"Číslovaný seznam": "Numbered list",
	"„citace“": "“quote”",
	"Citace": "Quote",
	"obrázek": "image",
	"galerie": "gallery",
	"Vložit obrázek z médií": "Insert an image from Media",
	"Fotogalerie": "Photo gallery",
	"Oddělovací čára": "Divider",
	"Odstranit formátování": "Remove formatting",
	" · čtení asi ": " · reading time about ",
	"Přepnout na zdrojový kód": "Switch to source code",
	"rozepsaný text uložen v prohlížeči ": "draft saved in your browser at ",
	"V prohlížeči je neuložená rozepsaná verze z ": "Your browser holds an unsaved draft from ",
	"Vybrat z médií": "Choose from Media",
	"Označte aspoň 2 fotky": "Select at least 2 photos",
	"Vložit galerii (": "Insert gallery (",
	"Klepnutím označte fotky v pořadí, v jakém mají jít za sebou. Soubory sem můžete i přetáhnout.": "Click photos in the order they should appear. You can also drop files here.",
	"Klepnutím obrázek vložíte. Soubory sem můžete i přetáhnout - nahrají se do zvolené složky.": "Click an image to insert it. You can also drop files here – they upload to the selected folder.",
	"Načítám…": "Loading…",
	"Všechna média": "All media",
	"Nezařazené": "Unsorted",
	"Složka: ": "Folder: ",
	"Tady zatím žádné obrázky nejsou.": "No images here yet.",
	"bez názvu": "untitled",
	"co je na obrázku vidět": "what the image shows",
	"Navrhnout popis asistentem": "Suggest a description with the assistant",
	"Asistent nic nenavrhl.": "The assistant suggested nothing.",
	"Mezititulek „": "Subheading “",
	"“ přeskakuje úroveň (H": "” skips a level (H",
	" bez H": " without H",
	"Prázdný mezititulek – smažte ho.": "Empty subheading – delete it.",
	"Odkaz „": "Link “",
	"“ neříká, kam vede. Odkazujte slovy, která dávají smysl i sama o sobě.": "” does not say where it leads. Use link text that makes sense on its own.",
	"Tabulka nemá záhlaví (buňky TH) – čtečka neumí říct, co který sloupec znamená.": "The table has no header (TH cells) – a screen reader cannot tell what each column means.",
	"Vložené video nebo rámec nemá název (atribut title).": "An embedded video or frame has no name (title attribute).",
	"Titulek má přes 110 znaků – ve výsledcích hledání i na sítích se ořízne.": "The headline is over 110 characters – it will be cut off in search results and on social networks.",
	"Titulek psaný VERZÁLKAMI se špatně čte a čtečky ho mohou hláskovat.": "An ALL-CAPS headline is hard to read and screen readers may spell it out.",
	"Kontrola přístupnosti": "Accessibility check",
	"✓ Obrázky mají popisy, nadpisy i odkazy jsou v pořádku.": "✓ Images have descriptions; headings and links are fine.",
	"Asistent": "Assistant",
	"Spojení s asistentem selhalo. Zkuste to znovu.": "The connection to the assistant failed. Try again.",
	"Navrhnout": "Suggest",
	"Návrhy titulku": "Headline suggestions",
	"Návrhy perexu": "Lead paragraph suggestions",
	"Korektura": "Proofread",
	"Popis pro vyhledávače": "Search engine description",
	"Návrh štítků": "Tag suggestions",
	"Použít": "Use",
	"Asistent nic nenavrhl. Zkuste to znovu.": "The assistant suggested nothing. Try again.",
	"✓ Asistent nenašel nic k opravě.": "✓ The assistant found nothing to fix.",
	" – úsek prochází formátováním, opravte ho prosím ručně": " – this passage spans formatting, please fix it by hand",
	"Opravit označené": "Fix selected",
	"Asistent zkontroluje pravopis, překlepy a typografii": "The assistant checks spelling, typos and typography",
	"✦ přemýšlím…": "✦ thinking…",
	"Ukládám…": "Saving…",
	"Média": "Media",
	"Nahrát nový": "Upload new",
	"Vložit galerii": "Insert gallery",
	"Zavřít": "Close",
	"Ano, provést": "Yes, do it",
	"Zrušit": "Cancel",
	"Obnovit ji": "Restore it",
	"Zahodit": "Discard",
	"Nic takového tu není.": "Nothing like that here.",
	"článek": "article",
	"Vyfotit": "Take a photo",
	"Běžný": "Regular",
	"Hotovo": "Done",
	"Jazyková verze": "Language version",
	"Nadpis": "Heading",
	"Nastavit": "Settings",
	"Obsah": "Content",
	"Odkazy": "Links",
	"Posunout níž": "Move down",
	"Posunout výš": "Move up",
	"Rubrika": "Section",
	"Stránky": "Pages",
	"Text": "Text",
	"Text tlačítka": "Button text",
	"Uložit": "Save",
	"Vzhled": "Appearance",
	"Výzva": "Call to action",
	"Zařízení": "Device",
	"ve všech": "in all",
	"Patička": "Footer",
	"Složka": "Folder",
	"Načíst další": "Load more",
	"Hledat v médiích…": "Search media…",
	"Hledat v médiích": "Search media",
	"Hledanému textu nic neodpovídá.": "Nothing matches your search.",
	"Období": "Period",
	"? Prvky ji ve struktuře ponechají, ale přestane mít vzhled.": "? Elements keep it in the structure, but it will lose its look.",
	"Adresa detailu": "Detail address",
	"Běžný stav": "Normal state",
	"Datum": "Date",
	"Deklarace navíc (vlastnost: hodnota;)": "Extra declarations (property: value;)",
	"Dolů": "Down",
	"Duplikovat (Ctrl+D)": "Duplicate (Ctrl+D)",
	"Historie": "History",
	"Hotové sekce": "Ready-made sections",
	"Koncept uložen": "Draft saved",
	"Kontejner nemá vlastní obsah – vložte do něj prvky, vzhled nastavíte v záložce Styl.": "A container has no content of its own – put elements into it and set its look in the Style tab.",
	"Mobil": "Mobile",
	"Nahoru": "Up",
	"Najetí myší": "Hover",
	"Nastavení stránky (název, adresa, SEO)": "Page settings (title, address, SEO)",
	"Načíst do konceptu": "Load into draft",
	"Neuloženo…": "Unsaved…",
	"Náhled stránky": "Page preview",
	"Název": "Name",
	"Odebrat": "Remove",
	"Odebrat třídu z prvku": "Remove class from element",
	"Otevřít publikovanou stránku": "Open the published page",
	"Pokračovat": "Continue",
	"Pokročilé": "Advanced",
	"Pole kolekce „%s“ – vložte do textu, obrázku nebo odkazu:": "Fields of collection “%s” – insert into text, image or link:",
	"Počítač": "Desktop",
	"Prvek nemá nastavitelný obsah.": "This element has no editable content.",
	"Prvky a struktura": "Elements and structure",
	"Prázdné pole = stejná hodnota jako na větší obrazovce (šedě).": "Empty field = same value as on the larger screen (grey).",
	"Publikované verze": "Published versions",
	"Publikovat": "Publish",
	"Publikováno": "Published",
	"Publikováno (stránka je zatím skrytá – zveřejníte ji v nastavení stránky)": "Published (the page is still hidden – make it public in the page settings)",
	"Publikováno – změny jsou na webu": "Published – changes are live",
	"Publikování se nepovedlo.": "Publishing failed.",
	"Přidat": "Add",
	"Přidat položku": "Add item",
	"Rozpracovaný koncept": "Draft in progress",
	"Sbalit / rozbalit": "Collapse / expand",
	"Server vrátil neočekávanou odpověď.": "The server returned an unexpected response.",
	"Skrýt na mobilu": "Hide on mobile",
	"Skrýt na tabletu i mobilu": "Hide on tablet and mobile",
	"Smazat": "Delete",
	"Smazat (Delete)": "Delete (Delete)",
	"Smazat třídu": "Delete class",
	"Smazat třídu .": "Delete class .",
	"Starší verze je v konceptu – publikujte ji, až bude hotová": "The older version is in the draft – publish it when ready",
	"Struktura": "Structure",
	"Stránka je prázdná. Přidejte sekci z panelu Přidat.": "The page is empty. Add a section from the Add panel.",
	"Styl": "Style",
	"Text s {{značkami}} kolekce upravte v panelu Obsah.": "Edit text with collection {{tags}} in the Content panel.",
	"Třída": "Class",
	"Třída sdílí vzhled mezi prvky na všech stránkách. Klepnutím na třídu ji upravíte.": "A class shares its look between elements on all pages. Click a class to edit it.",
	"Třída uložena s upozorněním": "Class saved with a warning",
	"Třída uložena – platí na všech stránkách": "Class saved – it applies on all pages",
	"Třídy": "Classes",
	"Uloženo, ale s upozorněními: ": "Saved, but with warnings: ",
	"Uložení se nepovedlo.": "Saving failed.",
	"Upravit třídu": "Edit class",
	"Upravujete: ": "Editing: ",
	"Verze": "Versions",
	"Viditelnost": "Visibility",
	"Vlastnosti": "Properties",
	"Vlastní CSS": "Custom CSS",
	"Vyberte prvek na plátně nebo ve struktuře. Dvojklikem na text ho upravíte přímo na stránce.": "Select an element on the canvas or in the structure. Double-click text to edit it right on the page.",
	"Vybrat nadřazený prvek (Esc)": "Select parent element (Esc)",
	"Zahodit všechny změny od posledního publikování? Nejde to vrátit.": "Discard all changes since the last publish? This cannot be undone.",
	"Zahodit změny": "Discard changes",
	"Zatím žádné starší verze.": "No older versions yet.",
	"Zkopírováno": "Copied",
	"Změny třídy se projeví u všech prvků s touto třídou na celém webu – hned po uložení, bez publikování.": "Class changes apply to all elements with this class across the site – immediately after saving, without publishing.",
	"Změny zahozeny": "Changes discarded",
	"Znovu (Ctrl+Shift+Z)": "Redo (Ctrl+Shift+Z)",
	"Zpět (Ctrl+Z)": "Undo (Ctrl+Z)",
	"Zpět na prvek": "Back to element",
	"beze změn proti webu": "no changes against the live site",
	"např. karta": "e.g. card",
	"při najetí myší": "on hover",
	"rozpracovaný koncept – návštěvníci vidí publikovanou verzi": "draft in progress – visitors see the published version",
	"zkopírováno": "copied",
	"Uložit jako komponentu": "Save as component",
	"Název komponenty (např. Karta služby):": "Component name (e.g. Service card):",
	"Komponenta uložena – úpravy v Komponentách se projeví všude, kde je použitá.": "Component saved – edits in Components apply everywhere it is used.",
	"Komponenta nemá vlastnosti – u všech použití vypadá stejně.": "The component has no properties – it looks the same everywhere.",
	"Vlastnosti komponenty „%s“ – vložte do textu, obrázku nebo odkazu:": "Component properties “%s” – insert into text, image or link:",
	"Přetažením přesunete": "Drag to move",
	"Hledat sekci…": "Search sections…",
	"Např.: Tři karty s našimi službami – kuchyně, skříně, schodiště. Ke každé krátký popis a odkaz na kontakt.": "E.g.: Three cards with our services – kitchens, wardrobes, staircases. A short description and a contact link for each.",
	"Vytvořit sekci s AI": "Create a section with AI",
	"Co má sekce obsahovat?": "What should the section contain?",
	"Asistent navrhne texty i rozložení ve stylu vašeho webu. Výsledek zkontrolujte – fakta (čísla, ceny, jména) doplňte sami.": "The assistant drafts texts and layout in your site's style. Check the result – fill in facts (numbers, prices, names) yourself.",
	"Asistent navrhuje sekci…": "The assistant is drafting a section…",
	"Asistent neodpověděl.": "The assistant did not respond.",
	"Sekce vložena. Upozornění: ": "Section inserted. Notes: ",
	"Sekce vložena – zkontrolujte texty.": "Section inserted – check the texts.",
	"Vytvořit": "Create",
	"kratší": "shorter",
	"delší": "longer",
	"formálněji": "more formal",
	"přátelštěji": "friendlier",
	"opravit chyby": "fix mistakes",
	"Přepsat s AI:": "Rewrite with AI:",
	"Asistent přepisuje text…": "The assistant is rewriting the text…",
	"Text přepsán – Ctrl+Z ho vrátí.": "Text rewritten – Ctrl+Z undoes it.",
	"Přihlášení vypršelo. Přihlaste se znovu v nové záložce – rozpracované změny zůstávají tady a uloží se samy.": "Your session has expired. Sign in again in a new tab – your unsaved changes stay here and will save automatically.",
	"Spojení se serverem selhalo.": "Could not connect to the server.",
	"Změny zatím nejsou uložené, zkusím to znovu za %s s.": "Changes are not saved yet, retrying in %s s.",
	"Přihlásit se": "Sign in",
	"Souběžná úprava": "Concurrent edit",
	"Načtěte novější verzi (vaše změny od posledního uložení se ztratí – zůstanou ve Zpět), nebo ji přepište svou.": "Load the newer version (your changes since the last save will be lost – they stay in Undo), or overwrite it with yours.",
	"Načtena novější verze": "Newer version loaded",
	"Načíst novější": "Load newer",
	"Přepsat mou verzí": "Overwrite with mine",
	"Publikuji…": "Publishing…",
	"Stránka": "Page",
	"Novinky": "News",
	"Skupina": "Group",
	"smazaná stránka": "deleted page",
	"Text v menu": "Menu text",
	"Přetažením změníte pořadí": "Drag to reorder",
	"Skrytá stránka se v menu na webu neukáže.": "A hidden page does not appear in the menu on the site.",
	"skrytá": "hidden",
	"Adresa odkazu": "Link address",
	"nové okno": "new window",
	"Do podmenu položky nad ní": "Into the submenu of the item above",
	"Z podmenu o úroveň výš": "Out of the submenu, one level up",
	"Odebrat z menu": "Remove from menu",
	"Vlastní odkaz potřebuje text i adresu.": "A custom link needs both text and an address.",
	"Skupina potřebuje text.": "A group needs text.",
	"novinka": "news item",
	"novinka – nevydaná": "news item – unpublished",
	"V tomto textu": "In this text",
	"Vložit fotogalerii - návštěvník si fotky prolistuje přes celou obrazovku": "Insert a photo gallery – visitors can browse the photos full screen",
	"…nebo najděte novinku webu": "…or find a news item on the site",
	"Popis obrázku pro nevidomé návštěvníky": "Image description for blind visitors",
	"Obrázek bez popisu – nevidomý návštěvník ani vyhledávač neví, co na něm je. Popis doplňte a potvrďte Enterem:": "Image without a description – neither a blind visitor nor a search engine knows what it shows. Add a description and confirm with Enter:",
	" nad sebou). Čtečky podle úrovní skládají osnovu textu.": " above it). Screen readers build the outline of the text from the levels.",
	"Chybí perex – výpis novinek a sdílení na sítích ho potřebují.": "The intro is missing – the news list and social sharing need it.",
	"Návrh se jen vloží do pole – můžete ho dál upravit. Nic se neuloží, dokud formulář neuložíte.": "The suggestion is only inserted into the field – you can keep editing it. Nothing is saved until you save the form.",
	"Asistent navrhne znění podle textu": "The assistant suggests wording based on the text",
	"Tlačítko „%s“ nikam nevede – doplňte odkaz.": "The button “%s” leads nowhere – add a link.",
	"Obrázek není vybraný – na webu se nezobrazí.": "No image selected – it will not appear on the site.",
	"Obrázek nemá popis pro nevidomé (alt).": "The image has no description for blind visitors (alt).",
	"Stránka nemá hlavní nadpis (h1) – vyhledávače i čtečky podle něj poznají, o čem je.": "The page has no main heading (h1) – search engines and screen readers use it to tell what the page is about.",
	"Stránka má víc hlavních nadpisů (h1) – nechte jen jeden.": "The page has more than one main heading (h1) – keep just one.",
	"Nadpis „%s“ přeskakuje úroveň (h%d → h%d).": "The heading “%s” skips a level (h%d → h%d).",
	"Kontrola před publikováním": "Pre-publish check",
	"Na stránce jsme našli věci, které stojí za opravu:": "We found a few things on the page worth fixing:",
	"Zpět k úpravám": "Back to editing",
	"Publikovat i tak": "Publish anyway",
	"Upozornění u jiných prvků: ": "Warnings on other elements: ",
	"ukázat": "show",
	"stránka webu, https://…, #kotva, mailto:, tel:": "site page, https://…, #anchor, mailto:, tel:",
	"Vybrat vlastní barvu": "Pick a custom colour",
	"Atributy (název=hodnota, na řádek; data-…, aria-…, title, lang, role, rel)": "Attributes (name=value, one per line; data-…, aria-…, title, lang, role, rel)",
	"Barevný přechod": "Gradient",
	"CSS jen pro tento prvek (vlastnost: hodnota;)": "CSS for this element only (property: value;)",
	"Hledat prvek nebo sekci": "Search elements or sections",
	"Hledat prvek nebo sekci…": "Search elements or sections…",
	"Kde je použitá": "Where it is used",
	"Moje sekce": "My sections",
	"Najetí": "Hover",
	"Najetí myší – platí i pro fokus z klávesnice": "Mouse hover – also applies to keyboard focus",
	"Nový název třídy": "New class name",
	"Název sekce": "Section name",
	"Objevení při rolování": "Reveal on scroll",
	"Odebrat sekci „%s“ z mých sekcí? Na stránkách, kde už je, zůstane.": "Remove the section “%s” from my sections? It stays on pages where it is already used.",
	"Odebrat z mých sekcí": "Remove from my sections",
	"Použito: ": "Used in: ",
	"Přejmenovat": "Rename",
	"Sekce je v panelu Přidat → Moje sekce.": "The section is in the Add panel → My sections.",
	"Sekce se objeví v panelu Přidat → Moje sekce. Každé vložení je samostatná kopie; když má být všude stejná, uložte ji jako komponentu.": "The section appears in the Add panel → My sections. Each insert is a separate copy; if it should be the same everywhere, save it as a component.",
	"Skrýt jen v editoru (na webu zůstane)": "Hide in the editor only (stays on the site)",
	"Stav prvku": "Element state",
	"Stisk": "Press",
	"Třída zatím není použitá v žádné publikované ani rozpracované stavbě.": "The class is not used in any published or draft build yet.",
	"Uložit do mých sekcí": "Save to my sections",
	"Uložit do mých sekcí (vložíte ji pak na jakoukoli stránku)": "Save to my sections (then insert it on any page)",
	"Vlastní CSS a atributy": "Custom CSS and attributes",
	"Vnější okraj vlevo": "Outer margin left",
	"Vnější okraj vpravo": "Outer margin right",
	"Zamknout: na plátně nepůjde vybrat ani přesunout": "Lock: cannot be selected or moved on the canvas",
	"Zjišťuji, kde je třída použitá…": "Checking where the class is used…",
	"hlavní → doplňková": "primary → secondary",
	"jemně shora": "soft from the top",
	"najetí myší a fokus": "hover and focus",
	"pozadí → plocha": "background → surface",
	"prolnutí": "fade",
	"přiblížení": "zoom in",
	"stisknutí": "press",
	"vyjetí zdola": "slide up",
	"ztmavení dole (na fotku)": "darken at the bottom (over a photo)",
	"záře v rohu": "glow in the corner",
	"Nový název musí být volný a psaný malými písmeny bez diakritiky (např. karta-velka).": "The new name must be unused and written in lowercase without accents (e.g. card-large).",
	"Třídu smí přejmenovat nebo smazat jen správce – mění vzhled celého webu.": "Only an administrator can rename or delete a class – it changes the look of the whole site.",
	"Sekce potřebuje název.": "The section needs a name.",
	"Prvek se nepodařilo uložit.": "The element could not be saved.",
	"Sekce smí odebrat jen správce.": "Only an administrator can remove sections.",
	"uložení sekce do knihovny": "section saved to library",
	"žádné": "none",
	"Klepněte na místo na stránce, kam prvek přesunout (horní nebo dolní část prvku = před nebo za, střed kontejneru = dovnitř). Esc zruší.": "Tap the place on the page to move the element to (top or bottom part of an element = before or after, middle of a container = inside). Esc cancels.",
	"Přetažením nebo klepnutím přesunete": "Drag or tap to move",
	"Přesunout klepnutím na místo (i na dotykové obrazovce)": "Move by tapping the target (works on touch screens too)",
	"Poskládat vlastní": "Compose your own",
	"Barva": "Colour",
	"Síla": "Strength",
	"Dovnitř": "Inset",
	"Šířka": "Width",
	"Čára": "Line",
	"plná": "solid",
	"čárkovaná": "dashed",
	"tečkovaná": "dotted",
	"dvojitá": "double",
	"Vodorovně": "Horizontal",
	"Svisle": "Vertical",
	"Rozostření": "Blur",
	"Roztažení": "Spread",
	"Oblast": "Area",
	"podle místa": "fit to space",
	"Řádků": "Rows",
	"Ubrat řádek": "Remove row",
	"Přidat řádek": "Add row",
	"Do buněk napište názvy oblastí (stejný název přes víc buněk = prvek se roztáhne). Vnořenému prvku pak zadejte „Oblast v mřížce“.": "Type area names into the cells (the same name across several cells = the element spans them). Then give the nested element its “Grid area”.",
	"Řádky mřížky": "Grid rows",
	"Oblasti mřížky": "Grid areas",
	"Oblast v mřížce (název)": "Grid area (name)",
	"Přes sloupce (v mřížce)": "Span columns (in grid)",
	"2 sloupce": "2 columns",
	"3 sloupce": "3 columns",
	"4 sloupce": "4 columns",
	"Přes řádky (v mřížce)": "Span rows (in grid)",
	"2 řádky": "2 rows",
	"3 řádky": "3 rows",
	"4 řádky": "4 rows",
	"Typografický styl": "Typography style",
	"Hlavní titulek": "Main title",
	"Nadpis sekce": "Section heading",
	"Podnadpis": "Subheading",
	"Perex": "Lead",
	"Běžný text": "Body text",
	"Drobný text": "Small text",
	"Nadtitulek": "Eyebrow",
	"volně v nadřazeném": "free within parent",
	"pevně v okně": "fixed in window",
	"Odshora": "From top",
	"Zdola": "From bottom",
	"Zleva": "From left",
	"Zprava": "From right",
	"Posun": "Offset",
	"nadzvednout": "lift",
	"nadzvednout víc": "lift more",
	"snížit": "lower",
	"vycentrovat (u volného umístění)": "centre (with free positioning)",
	"Měřítko": "Scale",
	"Otočení": "Rotation",
	"Plynulá změna (u najetí)": "Smooth change (on hover)",
	"rychlá": "fast",
	"pomalejší": "slower",
	"Typografické styly": "Typography styles",
	"Pojmenované styly textu, které v builderu vyberete u prvku (Styl → Typografie). Změna tady se projeví všude, kde styl je.": "Named text styles you pick for an element in the builder (Style → Typography). A change here applies everywhere the style is used.",
	"Velikost (krok škály)": "Size (scale step)",
	"Tloušťka": "Weight",
	"0 – základní písmo": "0 – base font",
	"Velikost: %s": "Size: %s",
	"Tloušťka: %s": "Weight: %s",
	"tenké": "light",
	"normální": "normal",
	"střední": "medium",
	"polotučné": "semibold",
	"tučné": "bold",
	"extra tučné": "extra bold",
	"Hledat na webu…": "Search the website…",
	"Hledat na webu": "Search the website",
	"z 5 · 120 recenzí": "out of 5 · 120 reviews",
	"Tlačítko nahoru (na webu vpravo dole)": "Back-to-top button (bottom right on the website)",
	"Zpět nahoru": "Back to top",
	"Odebírat": "Subscribe",
	"Pošleme vám jen novinky a nabídky. Odhlásit se můžete jedním kliknutím v každém e-mailu.": "We only send news and offers. You can unsubscribe with one click in every e-mail.",
	"Děkujeme! Poslali jsme vám e-mail s odkazem – odběr potvrďte kliknutím na něj.": "Thank you! We have sent you an e-mail with a link – click it to confirm your subscription.",
	"Zkontrolujte prosím e-mailovou adresu.": "Please check the e-mail address.",
	"Příliš mnoho pokusů za sebou. Zkuste to prosím za chvíli.": "Too many attempts in a row. Please try again in a moment.",
	"Váš e-mail": "Your e-mail",
	"vas@email.cz": "you@example.com",
	"Akce právě probíhá.": "The event is on now.",
	"Zadejte datum ve tvaru RRRR-MM-DD HH:MM.": "Enter the date as YYYY-MM-DD HH:MM.",
	"dní": "days",
	"hodin": "hours",
	"minut": "minutes",
	"sekund": "seconds",
	"Projekty dokončené v termínu": "Projects delivered on time",
	"Zákazníci, kteří se vracejí": "Returning customers",
	"spokojených zákazníků": "happy customers",
	"Hodnocení %s z 5": "Rated %s out of 5",
	"Potvrďte odběr novinek – %s": "Confirm your subscription – %s",
	"Dobrý den,": "Hello,",
	"pro potvrzení odběru novinek webu %s klikněte na odkaz:": "to confirm your subscription to news from %s, click the link:",
	"Pokud jste o odběr nežádali, e-mail ignorujte – bez potvrzení vám nic posílat nebudeme.": "If you did not ask to subscribe, ignore this e-mail – without confirmation we will not send you anything.",
	"Odběr je potvrzený": "Subscription confirmed",
	"Děkujeme, novinky vám budeme posílat na %s. Odhlásit se můžete odkazem v každém e-mailu.": "Thank you, we will send news to %s. You can unsubscribe using the link in every e-mail.",
	"Odhlášeno": "Unsubscribed",
	"Adresu %s jsme ze seznamu odběratelů smazali.": "We have removed %s from the subscriber list.",
	"Odkaz už neplatí": "The link is no longer valid",
	"Odkaz je neplatný nebo už byl použitý. Pokud chcete novinky odebírat, přihlaste se prosím znovu.": "The link is invalid or has already been used. If you want to receive news, please subscribe again.",
	"Zpět na úvod": "Back to the home page",
	"Velikost náhledu": "Preview size",
	"Vejít se": "Fit",
	"Široký monitor (1920 px)": "Wide monitor (1920 px)",
	"Nápověda a klávesové zkratky (?)": "Help and keyboard shortcuts (?)",
	"Nápověda": "Help",
	"Text „%s“ má na svém pozadí slabý kontrast (%d : 1) – špatně se čte.": "Text “%s” has low contrast against its background (%d : 1) – it is hard to read.",
	"Uložit koncept": "Save draft",
	"Zpět / znovu": "Undo / redo",
	"Duplikovat vybraný prvek": "Duplicate the selected element",
	"Kopírovat a vložit prvek (i mezi stránkami)": "Copy and paste an element (also between pages)",
	"Smazat vybraný prvek": "Delete the selected element",
	"Vybrat nadřazený prvek / zrušit přesun": "Select the parent element / cancel moving",
	"dvojklik": "double-click",
	"Upravit text přímo na plátně": "Edit text right on the canvas",
	"Pohyb ve Struktuře": "Move within Structure",
	"Tato nápověda": "This help",
	"Klávesové zkratky": "Keyboard shortcuts",
	"Prohlídka editoru": "Editor tour",
	"Prvky a hotové sekce": "Elements and ready-made sections",
	"Vlevo vyberete prvek nebo celou hotovou sekci. Klepnutím ho vložíte za vybraný prvek, přetažením kamkoli na stránku. Záložka Struktura ukáže stavbu stránky jako strom.": "On the left you pick an element or a whole ready-made section. Click to insert it after the selected element, drag it anywhere on the page. The Structure tab shows the page as a tree.",
	"Stránka, jak ji uvidí návštěvník": "The page as visitors will see it",
	"Klepnutím prvek vyberete, dvojklikem upravíte text. Nahoře přepnete náhled pro tablet a mobil – styl se pak mění jen pro danou šířku.": "Click to select an element, double-click to edit text. At the top you switch the preview to tablet and mobile – the style then changes only for that width.",
	"Obsah, styl a pokročilé": "Content, style and advanced",
	"Vpravo měníte text, odkazy, barvy, rozestupy i chování vybraného prvku. Barvy a velikosti berte z nabídky – drží jednotný vzhled webu.": "On the right you change the text, links, colours, spacing and behaviour of the selected element. Take colours and sizes from the list – they keep the website consistent.",
	"Ukládání a publikování": "Saving and publishing",
	"Změny se ukládají samy jako koncept. Návštěvníci je uvidí až po Publikovat – předtím vás upozorníme na chybějící odkazy, popisky a slabý kontrast.": "Changes save automatically as a draft. Visitors see them only after Publish – before that we warn you about missing links, descriptions and low contrast.",
	"Přeskočit": "Skip",
	"Další": "Next",
	"Styl zkopírován.": "Style copied.",
	"Kopírovat styl": "Copy style",
	"Vložit styl": "Paste style",
	"Podmínky zobrazení": "Display conditions",
	"Komu": "Show to",
	"všem": "everyone",
	"jen návštěvníkům (nepřihlášeným)": "visitors only (not signed in)",
	"jen přihlášeným do administrace": "only people signed in to the administration",
	"Zobrazit od": "Show from",
	"Zobrazit do (včetně)": "Show until (inclusive)",
	"Na plátně je prvek vidět vždy. Na webu se ukáže jen při splnění podmínek – třeba akční banner na týden.": "On the canvas the element is always visible. On the website it appears only when the conditions are met – for example a promotional banner for a week.",
	"Počítadlo": "Counter",
	"Ukazatele průběhu": "Progress bars",
	"Hodnocení": "Rating",
	"Odpočet": "Countdown",
	"Sociální sítě": "Social networks",
	"Vyhledávání": "Search",
	"Odběr novinek": "Newsletter sign-up",
	"Tlačítko nahoru": "Back-to-top button",
	"Velké číslo s popiskem, které se při zobrazení napočítá (roky praxe, zákazníci, projekty).": "A big number with a label that counts up when shown (years of experience, customers, projects).",
	"Pruhy s procenty – plnění cíle, podíl, úroveň dovedností.": "Bars with percentages – goal progress, share, skill level.",
	"Hvězdičky s hodnotou a počtem recenzí (např. z Google).": "Stars with a score and number of reviews (e.g. from Google).",
	"Zbývající čas do data – akce, otevření provozovny, uzávěrka přihlášek.": "Time remaining until a date – an event, an opening, a registration deadline.",
	"Ikony s odkazy na profily firmy (adresy z Nastavení).": "Icons linking to the company profiles (addresses from Settings).",
	"Pole pro hledání na webu – do záhlaví, na stránku 404 nebo k výpisu.": "A website search field – for the header, the 404 page or a listing.",
	"Pole pro e-mail s potvrzením odběru – adresy najdete v administraci v Odběratelích.": "An e-mail field with subscription confirmation – you will find the addresses under Subscribers in the administration.",
	"Plovoucí šipka zpět na začátek stránky – vložte ji do patičky.": "A floating arrow back to the top of the page – put it in the footer.",
	"Video na pozadí (MP4 nebo WebM z Médií, bez zvuku)": "Background video (MP4 or WebM from Media, no sound)",
	"Plakát (obrázek před spuštěním)": "Poster (image before playing)",
	"po odrolování poloviny stránky": "after scrolling half the page",
	"když se návštěvník chystá odejít": "when the visitor is about to leave",
	"Samo znovu": "Open again automatically",
	"jednou za návštěvu": "once per visit",
	"jednou za týden": "once a week",
	"už nikdy (po zavření)": "never again (after closing)",
	"Číslo": "Number",
	"Před číslem (např. „+“)": "Before the number (e.g. “+”)",
	"Za číslem (např. „ %“, „+“, „ let“)": "After the number (e.g. “ %”, “+”, “ years”)",
	"Popisek": "Label",
	"Ukazatele": "Bars",
	"Procenta": "Percent",
	"Hodnocení (0–5, např. 4,8)": "Rating (0–5, e.g. 4.8)",
	"Text vedle hvězdiček": "Text next to the stars",
	"Do kdy (RRRR-MM-DD HH:MM)": "Until (YYYY-MM-DD HH:MM)",
	"Text po skončení": "Text when finished",
	"Zobrazit i názvy sítí": "Show network names too",
	"Text v prázdném poli": "Placeholder text",
	"Tlačítko": "Button",
	"Text pod polem": "Text below the field",
	"Podmenu jako široký panel (mega menu)": "Submenu as a wide panel (mega menu)",
	"Obrázek pozadí při posunu": "Background image on scroll",
	"stojí (paralaxa)": "stays fixed (parallax)",
	"posouvá se s obsahem": "scrolls with content",
	"Prvek Odběr novinek v builderu: návštěvník zadá e-mail a potvrdí ho odkazem (double opt-in). Seznam odběratelů vyexportujete do rozesílacího nástroje.": "The Newsletter sign-up element in the builder: visitors enter an e-mail and confirm it by a link (double opt-in). You export the subscriber list to your mailing tool.",
	"Odběratelé": "Subscribers",
	"Odběratel byl smazán.": "The subscriber has been deleted.",
	"Přihlášen": "Subscribed",
	"Potvrzeno": "Confirmed",
	"Odkaz na odhlášení": "Unsubscribe link",
	"Adresy z prvku Odběr novinek. Za odběratele se počítá, kdo přihlášení potvrdil odkazem v e-mailu. Rozesílejte svým nástrojem – export obsahuje i odkaz na odhlášení.": "Addresses from the Newsletter sign-up element. Only people who confirmed by the link in the e-mail count as subscribers. Send with your own tool – the export includes the unsubscribe link.",
	"Hledat e-mail": "Search e-mail",
	"Export potvrzených (CSV)": "Export confirmed (CSV)",
	"Zatím žádní odběratelé.": "No subscribers yet.",
	"Vložte na web prvek Odběr novinek – třeba do patičky.": "Put the Newsletter sign-up element on the website – for example in the footer.",
	"potvrzený": "confirmed",
	"čeká na potvrzení": "awaiting confirmation",
	"Smazat adresu ze seznamu odběratelů?": "Remove the address from the subscriber list?",
	"Předchozí": "Previous",
	"Publikovat smí jen editor nebo správce. Změny zůstávají uložené jako koncept.": "Only an editor or administrator can publish. Your changes stay saved as a draft.",
	"Sdílenou třídu upravuje jen správce – změna se hned projeví na celém webu. Vzhled jednoho prvku nastavíte v jeho stylu.": "Only an administrator edits a shared class – a change applies to the whole website at once. Set the look of a single element in its style.",
	"Zveřejněné stránky upravuje, zveřejňuje a maže jen editor nebo správce. Můžete připravit novou skrytou stránku.": "Only an editor or administrator edits, publishes and deletes published pages. You can prepare a new hidden page.",
	"Novinka je vydaná – změny v ní uloží jen editor nebo správce. Požádejte je o úpravu.": "This news item is published – only an editor or administrator can save changes to it. Ask them to edit it.",
	"Web vyžaduje dvoufázové přihlášení – token vytvoříte, až si ho zapnete.": "The website requires two-step sign-in – you can create a token once you turn it on.",
	"Tato pole nemají platný tvar a neuložila se: %s. Opravte je prosím (jsou zvýrazněná), ostatní nastavení je uložené.": "These fields have an invalid format and were not saved: %s. Please correct them (they are highlighted); the other settings are saved.",
	"Vždy zapnuté jádro: Stránky, Kolekce, Média, Vzhled webu, Části webu, Menu, Komponenty, Uživatelé a Nastavení.": "Always-on core: Pages, Collections, Media, Site appearance, Site parts, Menu, Components, Users and Settings.",
	"Poptávky starší než zadaný počet měsíců se hned natrvalo smažou – i s přílohami. Opravdu uložit?": "Enquiries older than the given number of months will be permanently deleted right away – including attachments. Save anyway?",
	"Obnova se nezdařila: %s": "Restore failed: %s",
	"Databáze je zpět ve stavu před obnovou.": "The database is back in its state before the restore.",
	"Stav před obnovou je v záloze %s – obnovte ji prosím.": "The state before the restore is in backup %s – please restore it.",
	"Záloha je neúplná nebo poškozená (chybí konec souboru) – obnova byla zastavena.": "The backup is incomplete or damaged (the end of the file is missing) – the restore was stopped.",
	"Soubory webu jsou vrácené do stavu před aktualizací.": "The website files have been returned to their state before the update.",
	"Server neumí šifrované FTP (FTPS). Zálohu posílejte do úložiště S3, nebo si ji stahujte ručně.": "The server cannot use encrypted FTP (FTPS). Send backups to S3 storage, or download them manually.",
	"na FTP server se šifrováním FTPS (jiný hosting, domácí NAS)": "to an FTP server with FTPS encryption (another host, home NAS)",
	"Builder potřebuje větší obrazovku.": "The builder needs a larger screen.",
	"Stránky skládejte na počítači nebo tabletu. Na telefonu upravíte texty tlačítkem „Upravit zde“ přímo na webu.": "Build pages on a computer or tablet. On a phone, edit texts with the “Edit here” button right on the website.",
	"Zpět do administrace": "Back to the administration",
	"Popis pro nevidomé (alt)": "Description for blind users (alt)",
	"Vyskakovací okno": "Pop-up window",
	"Potvrzení odběru": "Confirm subscription",
	"Potvrďte prosím, že chcete dostávat novinky na %s.": "Please confirm that you want to receive news at %s.",
	"Potvrdit odběr": "Confirm subscription",
	"Odhlášení odběru": "Unsubscribe",
	"Opravdu už nechcete dostávat novinky na %s?": "Do you really no longer want to receive news at %s?",
	"Odhlásit odběr": "Unsubscribe",
	"štítek": "tag",
	"kategorie": "category",
	"moje sekce": "my section",
	"uživatel": "user",
	"bez ikony": "no icon",
	"Ikona vlevo od textu": "Icon left of the text",
	"Zvýraznění aktivní položky": "Current item highlight",
	"podbarvení": "background",
	"podtržení doplňkovou barvou": "underline in the secondary colour",
	"HTML značka": "HTML tag",
	"Název ve struktuře": "Name in Structure",
	"Kotva (id pro odkaz #…)": "Anchor (id for a #… link)",
	"Hlavní výzva": "Main call to action",
	"%s : 1": "%s:1",
	"Soubor je větší, než server dovoluje nahrát (nejvýš %s). Zmenšete ho, nebo požádejte správce hostingu o vyšší limit.": "The file is larger than the server allows (%s at most). Make it smaller or ask your hosting provider to raise the limit.",
	"Rozumím": "OK",
	"Komponenta je společná předloha: úprava v Komponentách se projeví všude, kde je použitá. Prvek na stránce se nahradí jejím použitím.": "A component is a shared template: editing it under Components changes it everywhere it is used. The element on this page is replaced by the component.",
	"Další akce": "More actions",
	"Zrušit přesun klepnutím": "Cancel move by tapping",
	"Vyberte video ve formátu MP4 nebo WebM.": "Choose a video in MP4 or WebM format."
};
