/* MiroCMS - překlad textů skriptů administrace (de). Klíčem je český text ze skriptů (funkce T()). */
window.MIROCMS_PREKLAD = {
	"rozepsaný text uložen i na serveru ": "Zwischenstand auch auf dem Server gespeichert um ",
	"Na serveru je neuložená rozepsaná verze z ": "Auf dem Server liegt ein nicht gespeicherter Zwischenstand von ",
	"Odkaz": "Link",
	"Adresa": "Adresse",
	"nebo": "oder",
	"…nebo najděte vlastní článek": "…oder einen eigenen Artikel suchen",
	"část titulku": "Teil des Titels",
	"otevřít v novém okně": "in neuem Fenster öffnen",
	"Vložit odkaz": "Link einfügen",
	"Zrušit odkaz": "Link entfernen",
	"Nic nenalezeno.": "Nichts gefunden.",
	"nevydaný": "nicht veröffentlicht",
	"tabulka": "Tabelle",
	"Vložit tabulku 3 × 3 se záhlavím; řádky a sloupce pak přidáte tlačítky nad tabulkou": "Tabelle 3 × 3 mit Kopfzeile einfügen; Zeilen und Spalten fügen Sie dann über die Schaltflächen oberhalb der Tabelle hinzu",
	"+ řádek": "+ Zeile",
	"+ sloupec": "+ Spalte",
	"− řádek": "− Zeile",
	"− sloupec": "− Spalte",
	"smazat tabulku": "Tabelle löschen",
	" slov": " Wörter",
	"Nahrání se nezdařilo. Zkontrolujte připojení a zkuste to znovu.": "Das Hochladen ist fehlgeschlagen. Prüfen Sie die Verbindung und versuchen Sie es erneut.",
	"Odstavec": "Absatz",
	"Mezititulek": "Zwischenüberschrift",
	"Menší mezititulek": "Kleinere Zwischenüberschrift",
	"Tučně (Ctrl+B)": "Fett (Strg+B)",
	"Kurzíva (Ctrl+I)": "Kursiv (Strg+I)",
	"odkaz": "Link",
	"Vložit odkaz (Ctrl+K)": "Link einfügen (Strg+K)",
	"• seznam": "• Liste",
	"1. seznam": "1. Liste",
	"Odrážkový seznam": "Aufzählung",
	"Číslovaný seznam": "Nummerierte Liste",
	"„citace“": "„Zitat“",
	"Citace": "Zitat",
	"obrázek": "Bild",
	"galerie": "Galerie",
	"Vložit obrázek z médií": "Bild aus den Medien einfügen",
	"Vložit fotogalerii - čtenář si fotky prolistuje přes celou obrazovku": "Bildergalerie einfügen - der Leser blättert die Fotos im Vollbild durch",
	"Oddělovací čára": "Trennlinie",
	"Odstranit formátování": "Formatierung entfernen",
	"Adresa odkazu (prázdné = odkaz zrušit):": "Adresse des Links (leer = Link entfernen):",
	" · čtení asi ": " · Lesezeit etwa ",
	"Přepnout na zdrojový kód": "Zum Quellcode wechseln",
	"rozepsaný text uložen v prohlížeči ": "Zwischenstand im Browser gespeichert um ",
	"V prohlížeči je neuložená rozepsaná verze z ": "Im Browser liegt ein nicht gespeicherter Zwischenstand von ",
	"Vybrat z médií": "Aus den Medien wählen",
	"Označte aspoň 2 fotky": "Mindestens 2 Fotos auswählen",
	"Vložit galerii (": "Galerie einfügen (",
	"Klepnutím označte fotky v pořadí, v jakém mají jít za sebou. Soubory sem můžete i přetáhnout.": "Wählen Sie die Fotos per Klick in der Reihenfolge aus, in der sie aufeinander folgen sollen. Sie können Dateien auch hierher ziehen.",
	"Klepnutím obrázek vložíte. Soubory sem můžete i přetáhnout - nahrají se do zvolené složky.": "Per Klick fügen Sie ein Bild ein. Sie können Dateien auch hierher ziehen - sie werden in den gewählten Ordner hochgeladen.",
	"Načítám…": "Wird geladen…",
	"Všechna média": "Alle Medien",
	"V tomto článku": "In diesem Artikel",
	"Nezařazené": "Nicht zugeordnet",
	"Složka: ": "Ordner: ",
	"Tady zatím žádné obrázky nejsou.": "Hier gibt es noch keine Bilder.",
	"bez názvu": "ohne Namen",
	"co je na obrázku vidět": "was auf dem Bild zu sehen ist",
	"Popis obrázku pro nevidomé čtenáře": "Bildbeschreibung für blinde Leser",
	"Obrázek bez popisu – nevidomý čtenář ani vyhledávač neví, co na něm je. Popis doplňte a potvrďte Enterem:": "Bild ohne Beschreibung – weder ein blinder Leser noch eine Suchmaschine weiß, was darauf zu sehen ist. Ergänzen Sie die Beschreibung und bestätigen Sie mit der Eingabetaste:",
	"Navrhnout popis asistentem": "Beschreibung vom Assistenten vorschlagen lassen",
	"Asistent nic nenavrhl.": "Der Assistent hat nichts vorgeschlagen.",
	"Mezititulek „": "Zwischenüberschrift „",
	"“ přeskakuje úroveň (H": "“ überspringt eine Ebene (H",
	" bez H": " ohne H",
	" nad sebou). Čtečky podle úrovní skládají osnovu článku.": " darüber). Screenreader bilden aus den Ebenen die Gliederung des Artikels.",
	"Prázdný mezititulek – smažte ho.": "Leere Zwischenüberschrift – löschen Sie sie.",
	"Odkaz „": "Link „",
	"“ neříká, kam vede. Odkazujte slovy, která dávají smysl i sama o sobě.": "“ sagt nicht, wohin er führt. Verlinken Sie Wörter, die auch für sich allein verständlich sind.",
	"Tabulka nemá záhlaví (buňky TH) – čtečka neumí říct, co který sloupec znamená.": "Die Tabelle hat keine Kopfzeile (TH-Zellen) – ein Screenreader kann nicht sagen, was die einzelnen Spalten bedeuten.",
	"Vložené video nebo rámec nemá název (atribut title).": "Ein eingebettetes Video oder ein Frame hat keinen Namen (Attribut title).",
	"Titulek má přes 110 znaků – ve výsledcích hledání i na sítích se ořízne.": "Der Titel hat über 110 Zeichen – in Suchergebnissen und in sozialen Netzwerken wird er abgeschnitten.",
	"Titulek psaný VERZÁLKAMI se špatně čte a čtečky ho mohou hláskovat.": "Ein Titel in GROSSBUCHSTABEN liest sich schlecht, und Screenreader buchstabieren ihn möglicherweise.",
	"Chybí perex – výpisy článků a sdílení na sítích ho potřebují.": "Der Vorspann fehlt – Artikelübersichten und das Teilen in sozialen Netzwerken brauchen ihn.",
	"Kontrola přístupnosti": "Prüfung der Barrierefreiheit",
	"✓ Obrázky mají popisy, nadpisy i odkazy jsou v pořádku.": "✓ Die Bilder haben Beschreibungen, Überschriften und Links sind in Ordnung.",
	"Asistent": "Assistent",
	"Spojení s asistentem selhalo. Zkuste to znovu.": "Die Verbindung zum Assistenten ist fehlgeschlagen. Versuchen Sie es erneut.",
	"Navrhnout": "Vorschlagen",
	"Návrhy titulku": "Titelvorschläge",
	"Návrhy perexu": "Vorschläge für den Vorspann",
	"Korektura": "Korrektur",
	"Shrnutí „Ve zkratce“": "Zusammenfassung „Kurz gefasst“",
	"Popis pro vyhledávače": "Beschreibung für Suchmaschinen",
	"Návrh štítků": "Schlagwortvorschläge",
	"Použít": "Übernehmen",
	"Asistent nic nenavrhl. Zkuste to znovu.": "Der Assistent hat nichts vorgeschlagen. Versuchen Sie es erneut.",
	"Návrh se jen vloží do pole – můžete ho dál upravit. Nic se neuloží, dokud článek neuložíte.": "Der Vorschlag wird nur in das Feld eingefügt – Sie können ihn weiter bearbeiten. Es wird nichts gespeichert, bis Sie den Artikel speichern.",
	"✓ Asistent nenašel nic k opravě.": "✓ Der Assistent hat nichts zu korrigieren gefunden.",
	" – úsek prochází formátováním, opravte ho prosím ručně": " – die Stelle erstreckt sich über Formatierungen, bitte von Hand korrigieren",
	"Opravit označené": "Ausgewählte korrigieren",
	"Asistent zkontroluje pravopis, překlepy a typografii": "Der Assistent prüft Rechtschreibung, Tippfehler und Typografie",
	"Asistent navrhne znění podle textu článku": "Der Assistent schlägt eine Formulierung anhand des Artikeltextes vor",
	"✦ přemýšlím…": "✦ denke nach…",
	"Ukládám…": "Wird gespeichert…",
	"Pořadí uloženo.": "Reihenfolge gespeichert.",
	"Pořadí se nepodařilo uložit.": "Die Reihenfolge konnte nicht gespeichert werden.",
	"Média": "Medien",
	"Nahrát nový": "Neues hochladen",
	"Vložit galerii": "Galerie einfügen",
	"Zavřít": "Schließen",
	"Ano, provést": "Ja, ausführen",
	"Zrušit": "Abbrechen",
	"Obnovit ji": "Wiederherstellen",
	"Zahodit": "Verwerfen",
	"Nic takového tu není.": "So etwas gibt es hier nicht.",
	"článek": "Artikel",
	"článek – nevydaný": "Artikel – nicht veröffentlicht",
	"Vyfotit": "Foto aufnehmen",
	" Blok dočasně skrýt": " Block vorübergehend ausblenden",
	" Zobrazit nadpis na webu": " Überschrift auf der Website anzeigen",
	"+ další odkaz": "+ weiterer Link",
	"/o-nas nebo https://…": "/ueber-uns oder https://…",
	"Bannery se spravují v sekci Reklama.": "Banner werden im Bereich Werbung verwaltet.",
	"Blok se přidá do zóny „": "Der Block kommt in die Zone „",
	"Blok smazán": "Block gelöscht",
	"Bloky přetahujte myší. Najetím na blok se ukáže jeho ovládání.": "Ziehen Sie die Blöcke mit der Maus. Wenn Sie mit dem Mauszeiger über einen Block fahren, erscheinen seine Bedienelemente.",
	"Běžný": "Normal",
	"Co chcete přidat?": "Was möchten Sie hinzufügen?",
	"Hotovo": "Fertig",
	"Jazyková verze": "Sprachversion",
	"Jedna až dvě věty. Prázdné = výchozí text.": "Ein bis zwei Sätze. Leer = Standardtext.",
	"Jen v rubrice": "Nur im Ressort",
	"Kam tlačítko vede": "Wohin die Schaltfläche führt",
	"Kdy a kde blok zobrazit": "Wann und wo der Block angezeigt wird",
	"Kolik položek": "Anzahl der Einträge",
	"Nadpis": "Überschrift",
	"Nastavit": "Einstellen",
	"Nejnovější ze všech rubrik": "Neueste aus allen Ressorts",
	"Obsah": "Inhalt",
	"Odebrat odkaz": "Link entfernen",
	"Odkazy": "Links",
	"Platební odkaz (Stripe, Donio, Darujme, Ko-fi…) nebo vlastní stránka s číslem účtu a QR kódem.": "Zahlungslink (Stripe, Donio, Darujme, Ko-fi…) oder eine eigene Seite mit Kontonummer und QR-Code.",
	"Podbarvený": "Farbig hinterlegt",
	"Podpořit redakci": "Redaktion unterstützen",
	"Posunout níž": "Nach unten verschieben",
	"Posunout výš": "Nach oben verschieben",
	"Pořadí se nepodařilo uložit": "Die Reihenfolge konnte nicht gespeichert werden",
	"Pořadí uloženo": "Reihenfolge gespeichert",
	"Reklamní pozice": "Anzeigenposition",
	"Rozvržení:": "Layout:",
	"Rubrika": "Ressort",
	"Smazat blok": "Block löschen",
	"Smazat blok „": "Löschen des Blocks „",
	"Stránky": "Seiten",
	"Text": "Text",
	"Text odkazu": "Linktext",
	"Text tlačítka": "Text der Schaltfläche",
	"Text, obrázek z médií nebo vložený kód (přepněte na HTML).": "Text, ein Bild aus den Medien oder eingebetteter Code (wechseln Sie zu HTML).",
	"Uložení se nezdařilo": "Speichern fehlgeschlagen",
	"Uložit": "Speichern",
	"V rámečku": "Mit Rahmen",
	"Vzhled": "Aussehen",
	"Výzva": "Aufruf",
	"Zařízení": "Gerät",
	"Zvýrazněný nadpis": "Hervorgehobene Überschrift",
	"ve všech": "in allen",
	"Úprava bloků": "Blöcke bearbeiten",
	"“. Nastavení můžete kdykoli změnit.": "“. Die Einstellungen können Sie jederzeit ändern.",
	"Hlavička": "Kopfzeile",
	"Levý sloupec": "Linke Spalte",
	"Nad obsahem": "Über dem Inhalt",
	"Pod obsahem": "Unter dem Inhalt",
	"Pravý sloupec": "Rechte Spalte",
	"Patička": "Fußzeile",
	"+ Přidat blok": "+ Block hinzufügen",
	"Složka": "Ordner",
	"Načíst další": "Weitere laden",
	"Hledat v médiích…": "Medien durchsuchen…",
	"Hledat v médiích": "Medien durchsuchen",
	"Hledanému textu nic neodpovídá.": "Keine Treffer für Ihre Suche.",
	"Období": "Zeitraum",
	"Počítá se z vlastní statistiky návštěv; bez ní podle celkového počtu přečtení.": "Gezählt aus der eigenen Besuchsstatistik; ohne sie nach der Gesamtzahl der Aufrufe."
};
