/* MiroCMS - překlad textů skriptů administrace (en). Klíčem je český text ze skriptů (funkce T()). */
window.MIROCMS_PREKLAD = {
	"rozepsaný text uložen i na serveru ": "draft also saved on the server at ",
	"Na serveru je neuložená rozepsaná verze z ": "The server holds an unsaved draft from ",

	"Odkaz": "Link",
	"Adresa": "Address",
	"nebo": "or",
	"…nebo najděte vlastní článek": "…or find one of your articles",
	"část titulku": "part of the headline",
	"otevřít v novém okně": "open in a new window",
	"Vložit odkaz": "Insert link",
	"Zrušit odkaz": "Remove link",
	"Nic nenalezeno.": "Nothing found.",
	"nevydaný": "unpublished",

	"tabulka": "table",
	"Vložit tabulku 3 × 3 se záhlavím; řádky a sloupce pak přidáte tlačítky nad tabulkou": "Insert a 3 × 3 table with a header; add rows and columns with the buttons above the table",
	"+ řádek": "+ row",
	"+ sloupec": "+ column",
	"− řádek": "− row",
	"− sloupec": "− column",
	"smazat tabulku": "delete table",

	" slov": " words",
	"Nahrání se nezdařilo. Zkontrolujte připojení a zkuste to znovu.": "Upload failed. Check your connection and try again.",
	"Odstavec": "Paragraph",
	"Mezititulek": "Subheading",
	"Menší mezititulek": "Smaller subheading",
	"Tučně (Ctrl+B)": "Bold (Ctrl+B)",
	"Kurzíva (Ctrl+I)": "Italic (Ctrl+I)",
	"odkaz": "link",
	"Vložit odkaz (Ctrl+K)": "Insert link (Ctrl+K)",
	"• seznam": "• list",
	"1. seznam": "1. list",
	"Odrážkový seznam": "Bulleted list",
	"Číslovaný seznam": "Numbered list",
	"„citace“": "“quote”",
	"Citace": "Quote",
	"obrázek": "image",
	"galerie": "gallery",
	"Vložit obrázek z médií": "Insert an image from Media",
	"Fotogalerie": "Photo gallery",
	"Vložit fotogalerii - čtenář si fotky prolistuje přes celou obrazovku": "Insert a photo gallery – readers browse the photos full screen",
	"Oddělovací čára": "Divider",
	"Odstranit formátování": "Remove formatting",
	"Adresa odkazu (prázdné = odkaz zrušit):": "Link URL (empty = remove the link):",
	" · čtení asi ": " · reading time about ",
	"Přepnout na zdrojový kód": "Switch to source code",
	"rozepsaný text uložen v prohlížeči ": "draft saved in your browser at ",
	"V prohlížeči je neuložená rozepsaná verze z ": "Your browser holds an unsaved draft from ",
	"Vybrat z médií": "Choose from Media",
	"Označte aspoň 2 fotky": "Select at least 2 photos",
	"Vložit galerii (": "Insert gallery (",
	"Klepnutím označte fotky v pořadí, v jakém mají jít za sebou. Soubory sem můžete i přetáhnout.": "Click photos in the order they should appear. You can also drop files here.",
	"Klepnutím obrázek vložíte. Soubory sem můžete i přetáhnout - nahrají se do zvolené složky.": "Click an image to insert it. You can also drop files here – they upload to the selected folder.",
	"Načítám…": "Loading…",
	"Všechna média": "All media",
	"V tomto článku": "In this article",
	"Nezařazené": "Unsorted",
	"Složka: ": "Folder: ",
	"Tady zatím žádné obrázky nejsou.": "No images here yet.",
	"bez názvu": "untitled",
	"co je na obrázku vidět": "what the image shows",
	"Popis obrázku pro nevidomé čtenáře": "Image description for blind readers",
	"Obrázek bez popisu – nevidomý čtenář ani vyhledávač neví, co na něm je. Popis doplňte a potvrďte Enterem:": "Image without a description – neither blind readers nor search engines know what it shows. Add one and press Enter:",
	"Navrhnout popis asistentem": "Suggest a description with the assistant",
	"Asistent nic nenavrhl.": "The assistant suggested nothing.",
	"Mezititulek „": "Subheading “",
	"“ přeskakuje úroveň (H": "” skips a level (H",
	" bez H": " without H",
	" nad sebou). Čtečky podle úrovní skládají osnovu článku.": " above it). Screen readers build the article outline from heading levels.",
	"Prázdný mezititulek – smažte ho.": "Empty subheading – delete it.",
	"Odkaz „": "Link “",
	"“ neříká, kam vede. Odkazujte slovy, která dávají smysl i sama o sobě.": "” does not say where it leads. Use link text that makes sense on its own.",
	"Tabulka nemá záhlaví (buňky TH) – čtečka neumí říct, co který sloupec znamená.": "The table has no header (TH cells) – a screen reader cannot tell what each column means.",
	"Vložené video nebo rámec nemá název (atribut title).": "An embedded video or frame has no name (title attribute).",
	"Titulek má přes 110 znaků – ve výsledcích hledání i na sítích se ořízne.": "The headline is over 110 characters – it will be cut off in search results and on social networks.",
	"Titulek psaný VERZÁLKAMI se špatně čte a čtečky ho mohou hláskovat.": "An ALL-CAPS headline is hard to read and screen readers may spell it out.",
	"Chybí perex – výpisy článků a sdílení na sítích ho potřebují.": "The lead paragraph is missing – listings and social sharing need it.",
	"Kontrola přístupnosti": "Accessibility check",
	"✓ Obrázky mají popisy, nadpisy i odkazy jsou v pořádku.": "✓ Images have descriptions; headings and links are fine.",
	"Asistent": "Assistant",
	"Spojení s asistentem selhalo. Zkuste to znovu.": "The connection to the assistant failed. Try again.",
	"Navrhnout": "Suggest",
	"Návrhy titulku": "Headline suggestions",
	"Návrhy perexu": "Lead paragraph suggestions",
	"Korektura": "Proofread",
	"Shrnutí „Ve zkratce“": "“In brief” summary",
	"Popis pro vyhledávače": "Search engine description",
	"Návrh štítků": "Tag suggestions",
	"Použít": "Use",
	"Asistent nic nenavrhl. Zkuste to znovu.": "The assistant suggested nothing. Try again.",
	"Návrh se jen vloží do pole – můžete ho dál upravit. Nic se neuloží, dokud článek neuložíte.": "The suggestion is only placed in the field – you can edit it further. Nothing is saved until you save the article.",
	"✓ Asistent nenašel nic k opravě.": "✓ The assistant found nothing to fix.",
	" – úsek prochází formátováním, opravte ho prosím ručně": " – this passage spans formatting, please fix it by hand",
	"Opravit označené": "Fix selected",
	"Asistent zkontroluje pravopis, překlepy a typografii": "The assistant checks spelling, typos and typography",
	"Asistent navrhne znění podle textu článku": "The assistant suggests wording based on the article text",
	"✦ přemýšlím…": "✦ thinking…",
	"Ukládám…": "Saving…",
	"Pořadí uloženo.": "Order saved.",
	"Pořadí se nepodařilo uložit.": "The order could not be saved.",
	"Média": "Media",
	"Nahrát nový": "Upload new",
	"Vložit galerii": "Insert gallery",
	"Zavřít": "Close",
	"Ano, provést": "Yes, do it",
	"Zrušit": "Cancel",
	"Obnovit ji": "Restore it",
	"Zahodit": "Discard",
	"Nic takového tu není.": "Nothing like that here.",
	"článek": "article",
	"článek – nevydaný": "article – unpublished",
	"Vyfotit": "Take a photo",
	" Blok dočasně skrýt": " Hide the block temporarily",
	" Zobrazit nadpis na webu": " Show the heading on the site",
	"+ další odkaz": "+ another link",
	"/o-nas nebo https://…": "/about or https://…",
	"Bannery se spravují v sekci Reklama.": "Banners are managed in the Ads section.",
	"Blok se přidá do zóny „": "The block will be added to the zone “",
	"Blok smazán": "Block deleted",
	"Bloky přetahujte myší. Najetím na blok se ukáže jeho ovládání.": "Drag blocks with the mouse. Hover over a block to see its controls.",
	"Běžný": "Regular",
	"Co chcete přidat?": "What do you want to add?",
	"Hotovo": "Done",
	"Jazyková verze": "Language version",
	"Jedna až dvě věty. Prázdné = výchozí text.": "One or two sentences. Empty = default text.",
	"Jen v rubrice": "Only in section",
	"Kam tlačítko vede": "Where the button leads",
	"Kdy a kde blok zobrazit": "When and where to show the block",
	"Kolik položek": "Number of items",
	"Nadpis": "Heading",
	"Nastavit": "Settings",
	"Nejnovější ze všech rubrik": "Latest from all sections",
	"Obsah": "Content",
	"Odebrat odkaz": "Remove link",
	"Odkazy": "Links",
	"Platební odkaz (Stripe, Donio, Darujme, Ko-fi…) nebo vlastní stránka s číslem účtu a QR kódem.": "A payment link (Stripe, Donio, Ko-fi…) or your own page with an account number and a QR code.",
	"Podbarvený": "Tinted",
	"Podpořit redakci": "Support the newsroom",
	"Posunout níž": "Move down",
	"Posunout výš": "Move up",
	"Pořadí se nepodařilo uložit": "The order could not be saved",
	"Pořadí uloženo": "Order saved",
	"Reklamní pozice": "Ad position",
	"Rozvržení:": "Layout:",
	"Rubrika": "Section",
	"Smazat blok": "Delete block",
	"Smazat blok „": "Delete the block “",
	"Stránky": "Pages",
	"Text": "Text",
	"Text odkazu": "Link text",
	"Text tlačítka": "Button text",
	"Text, obrázek z médií nebo vložený kód (přepněte na HTML).": "Text, an image from Media or embedded code (switch to HTML).",
	"Uložení se nezdařilo": "Saving failed",
	"Uložit": "Save",
	"V rámečku": "Framed",
	"Vzhled": "Appearance",
	"Výzva": "Call to action",
	"Zařízení": "Device",
	"Zvýrazněný nadpis": "Highlighted heading",
	"ve všech": "in all",
	"Úprava bloků": "Editing blocks",
	"“. Nastavení můžete kdykoli změnit.": "”. You can change the settings at any time.",
	"Hlavička": "Header",
	"Levý sloupec": "Left column",
	"Nad obsahem": "Above content",
	"Pod obsahem": "Below content",
	"Pravý sloupec": "Right column",
	"Patička": "Footer",
	"+ Přidat blok": "+ Add block",
	"Složka": "Folder",
	"Načíst další": "Load more",
	"Hledat v médiích…": "Search media…",
	"Hledat v médiích": "Search media",
	"Hledanému textu nic neodpovídá.": "Nothing matches your search.",
	"Období": "Period",
	"Počítá se z vlastní statistiky návštěv; bez ní podle celkového počtu přečtení.": "Counted from the built-in visit statistics; without them, by the total number of reads.",
	"? Prvky ji ve struktuře ponechají, ale přestane mít vzhled.": "? Elements keep it in the structure, but it will lose its look.",
	"Adresa detailu": "Detail address",
	"Běžný stav": "Normal state",
	"Datum": "Date",
	"Deklarace navíc (vlastnost: hodnota;)": "Extra declarations (property: value;)",
	"Dolů": "Down",
	"Duplikovat (Ctrl+D)": "Duplicate (Ctrl+D)",
	"Historie": "History",
	"Hotové sekce": "Ready-made sections",
	"Koncept uložen": "Draft saved",
	"Kontejner nemá vlastní obsah – vložte do něj prvky, vzhled nastavíte v záložce Styl.": "A container has no content of its own – put elements into it and set its look in the Style tab.",
	"Mobil": "Mobile",
	"Nahoru": "Up",
	"Najetí myší": "Hover",
	"Nastavení stránky (název, adresa, SEO)": "Page settings (title, address, SEO)",
	"Načíst do konceptu": "Load into draft",
	"Neuloženo…": "Unsaved…",
	"Náhled stránky": "Page preview",
	"Název": "Name",
	"Odebrat": "Remove",
	"Odebrat třídu z prvku": "Remove class from element",
	"Otevřít publikovanou stránku": "Open the published page",
	"Pokračovat": "Continue",
	"Pokročilé": "Advanced",
	"Pole kolekce „%s“ – vložte do textu, obrázku nebo odkazu:": "Fields of collection “%s” – insert into text, image or link:",
	"Počítač": "Desktop",
	"Prvek nemá nastavitelný obsah.": "This element has no editable content.",
	"Prvky a struktura": "Elements and structure",
	"Prázdné pole = stejná hodnota jako na větší obrazovce (šedě).": "Empty field = same value as on the larger screen (grey).",
	"Publikované verze": "Published versions",
	"Publikovat": "Publish",
	"Publikováno": "Published",
	"Publikováno (stránka je zatím skrytá – zveřejníte ji v nastavení stránky)": "Published (the page is still hidden – make it public in the page settings)",
	"Publikováno – změny jsou na webu": "Published – changes are live",
	"Publikování se nepovedlo.": "Publishing failed.",
	"Přidat": "Add",
	"Přidat položku": "Add item",
	"Rozpracovaný koncept": "Draft in progress",
	"Sbalit / rozbalit": "Collapse / expand",
	"Server vrátil neočekávanou odpověď.": "The server returned an unexpected response.",
	"Skrýt na mobilu": "Hide on mobile",
	"Skrýt na tabletu i mobilu": "Hide on tablet and mobile",
	"Smazat": "Delete",
	"Smazat (Delete)": "Delete (Delete)",
	"Smazat třídu": "Delete class",
	"Smazat třídu .": "Delete class .",
	"Spojení se serverem selhalo – změny zatím nejsou uložené.": "Connection to the server failed – changes are not saved yet.",
	"Starší verze je v konceptu – publikujte ji, až bude hotová": "The older version is in the draft – publish it when ready",
	"Struktura": "Structure",
	"Stránka je prázdná. Přidejte sekci z panelu Přidat.": "The page is empty. Add a section from the Add panel.",
	"Styl": "Style",
	"Text s {{značkami}} kolekce upravte v panelu Obsah.": "Edit text with collection {{tags}} in the Content panel.",
	"Třída": "Class",
	"Třída sdílí vzhled mezi prvky na všech stránkách. Klepnutím na třídu ji upravíte.": "A class shares its look between elements on all pages. Click a class to edit it.",
	"Třída uložena s upozorněním": "Class saved with a warning",
	"Třída uložena – platí na všech stránkách": "Class saved – it applies on all pages",
	"Třídy": "Classes",
	"Uloženo, ale s upozorněními: ": "Saved, but with warnings: ",
	"Uložení se nepovedlo.": "Saving failed.",
	"Upravit třídu": "Edit class",
	"Upravujete: ": "Editing: ",
	"Verze": "Versions",
	"Viditelnost": "Visibility",
	"Vlastnosti": "Properties",
	"Vlastní CSS": "Custom CSS",
	"Vyberte prvek na plátně nebo ve struktuře. Dvojklikem na text ho upravíte přímo na stránce.": "Select an element on the canvas or in the structure. Double-click text to edit it right on the page.",
	"Vybrat nadřazený prvek (Esc)": "Select parent element (Esc)",
	"Zahodit všechny změny od posledního publikování? Nejde to vrátit.": "Discard all changes since the last publish? This cannot be undone.",
	"Zahodit změny": "Discard changes",
	"Zatím žádné starší verze.": "No older versions yet.",
	"Zkopírováno": "Copied",
	"Změny třídy se projeví u všech prvků s touto třídou na celém webu – hned po uložení, bez publikování.": "Class changes apply to all elements with this class across the site – immediately after saving, without publishing.",
	"Změny zahozeny": "Changes discarded",
	"Znovu (Ctrl+Shift+Z)": "Redo (Ctrl+Shift+Z)",
	"Zpět (Ctrl+Z)": "Undo (Ctrl+Z)",
	"Zpět na prvek": "Back to element",
	"beze změn proti webu": "no changes against the live site",
	"např. karta": "e.g. card",
	"při najetí myší": "on hover",
	"rozpracovaný koncept – návštěvníci vidí publikovanou verzi": "draft in progress – visitors see the published version",
	"zkopírováno": "copied",
	"Uložit jako komponentu": "Save as component",
	"Název komponenty (např. Karta služby):": "Component name (e.g. Service card):",
	"Komponenta uložena – úpravy v Komponentách se projeví všude, kde je použitá.": "Component saved – edits in Components apply everywhere it is used.",
	"Komponenta nemá vlastnosti – u všech použití vypadá stejně.": "The component has no properties – it looks the same everywhere.",
	"Vlastnosti komponenty „%s“ – vložte do textu, obrázku nebo odkazu:": "Component properties “%s” – insert into text, image or link:",
	"Přetažením přesunete": "Drag to move",
	"Hledat sekci…": "Search sections…",
	"Např.: Tři karty s našimi službami – kuchyně, skříně, schodiště. Ke každé krátký popis a odkaz na kontakt.": "E.g.: Three cards with our services – kitchens, wardrobes, staircases. A short description and a contact link for each.",
	"Vytvořit sekci s AI": "Create a section with AI",
	"Co má sekce obsahovat?": "What should the section contain?",
	"Asistent navrhne texty i rozložení ve stylu vašeho webu. Výsledek zkontrolujte – fakta (čísla, ceny, jména) doplňte sami.": "The assistant drafts texts and layout in your site's style. Check the result – fill in facts (numbers, prices, names) yourself.",
	"Asistent navrhuje sekci…": "The assistant is drafting a section…",
	"Asistent neodpověděl.": "The assistant did not respond.",
	"Sekce vložena. Upozornění: ": "Section inserted. Notes: ",
	"Sekce vložena – zkontrolujte texty.": "Section inserted – check the texts.",
	"Vytvořit": "Create",
	"kratší": "shorter",
	"delší": "longer",
	"formálněji": "more formal",
	"přátelštěji": "friendlier",
	"opravit chyby": "fix mistakes",
	"Přepsat s AI:": "Rewrite with AI:",
	"Asistent přepisuje text…": "The assistant is rewriting the text…",
	"Text přepsán – Ctrl+Z ho vrátí.": "Text rewritten – Ctrl+Z undoes it.",
	"Přihlášení vypršelo. Přihlaste se znovu v nové záložce – rozpracované změny zůstávají tady a uloží se samy.": "Your session has expired. Sign in again in a new tab – your unsaved changes stay here and will save automatically.",
	"Spojení se serverem selhalo.": "Could not connect to the server.",
	"Změny zatím nejsou uložené, zkusím to znovu za %s s.": "Changes are not saved yet, retrying in %s s.",
	"Přihlásit se": "Sign in",
	"Souběžná úprava": "Concurrent edit",
	"Načtěte novější verzi (vaše změny od posledního uložení se ztratí – zůstanou ve Zpět), nebo ji přepište svou.": "Load the newer version (your changes since the last save will be lost – they stay in Undo), or overwrite it with yours.",
	"Načtena novější verze": "Newer version loaded",
	"Načíst novější": "Load newer",
	"Přepsat mou verzí": "Overwrite with mine",
	"Publikuji…": "Publishing…"
};
